/*
Baserow API spec

For more information about our REST API, please visit [this page](https://baserow.io/docs/apis%2Frest-api).  For more information about our deprecation policy, please visit [this page](https://baserow.io/docs/apis%2Fdeprecations).

API version: 1.18.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the ExampleBatchRowsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ExampleBatchRowsResponse{}

// ExampleBatchRowsResponse struct for ExampleBatchRowsResponse
type ExampleBatchRowsResponse struct {
	Items []ExampleRowResponseSerializerWithUserFieldNames `json:"items"`
}

// NewExampleBatchRowsResponse instantiates a new ExampleBatchRowsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewExampleBatchRowsResponse(items []ExampleRowResponseSerializerWithUserFieldNames) *ExampleBatchRowsResponse {
	this := ExampleBatchRowsResponse{}
	this.Items = items
	return &this
}

// NewExampleBatchRowsResponseWithDefaults instantiates a new ExampleBatchRowsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewExampleBatchRowsResponseWithDefaults() *ExampleBatchRowsResponse {
	this := ExampleBatchRowsResponse{}
	return &this
}

// GetItems returns the Items field value
func (o *ExampleBatchRowsResponse) GetItems() []ExampleRowResponseSerializerWithUserFieldNames {
	if o == nil {
		var ret []ExampleRowResponseSerializerWithUserFieldNames
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *ExampleBatchRowsResponse) GetItemsOk() ([]ExampleRowResponseSerializerWithUserFieldNames, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *ExampleBatchRowsResponse) SetItems(v []ExampleRowResponseSerializerWithUserFieldNames) {
	o.Items = v
}

func (o ExampleBatchRowsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ExampleBatchRowsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["items"] = o.Items
	return toSerialize, nil
}

type NullableExampleBatchRowsResponse struct {
	value *ExampleBatchRowsResponse
	isSet bool
}

func (v NullableExampleBatchRowsResponse) Get() *ExampleBatchRowsResponse {
	return v.value
}

func (v *NullableExampleBatchRowsResponse) Set(val *ExampleBatchRowsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableExampleBatchRowsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableExampleBatchRowsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExampleBatchRowsResponse(val *ExampleBatchRowsResponse) *NullableExampleBatchRowsResponse {
	return &NullableExampleBatchRowsResponse{value: val, isSet: true}
}

func (v NullableExampleBatchRowsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExampleBatchRowsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


