/*
Baserow API spec

For more information about our REST API, please visit [this page](https://baserow.io/docs/apis%2Frest-api).  For more information about our deprecation policy, please visit [this page](https://baserow.io/docs/apis%2Fdeprecations).

API version: 1.18.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the TableWebhookTestCallResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TableWebhookTestCallResponse{}

// TableWebhookTestCallResponse struct for TableWebhookTestCallResponse
type TableWebhookTestCallResponse struct {
	// A text copy of the request headers and body.
	Request string `json:"request"`
	// A text copy of the response headers and body.
	Response string `json:"response"`
	// The HTTP response status code.
	StatusCode int32 `json:"status_code"`
	// Indicates whether the provided URL could be reached.
	IsUnreachable bool `json:"is_unreachable"`
}

// NewTableWebhookTestCallResponse instantiates a new TableWebhookTestCallResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTableWebhookTestCallResponse(request string, response string, statusCode int32, isUnreachable bool) *TableWebhookTestCallResponse {
	this := TableWebhookTestCallResponse{}
	this.Request = request
	this.Response = response
	this.StatusCode = statusCode
	this.IsUnreachable = isUnreachable
	return &this
}

// NewTableWebhookTestCallResponseWithDefaults instantiates a new TableWebhookTestCallResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTableWebhookTestCallResponseWithDefaults() *TableWebhookTestCallResponse {
	this := TableWebhookTestCallResponse{}
	return &this
}

// GetRequest returns the Request field value
func (o *TableWebhookTestCallResponse) GetRequest() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Request
}

// GetRequestOk returns a tuple with the Request field value
// and a boolean to check if the value has been set.
func (o *TableWebhookTestCallResponse) GetRequestOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Request, true
}

// SetRequest sets field value
func (o *TableWebhookTestCallResponse) SetRequest(v string) {
	o.Request = v
}

// GetResponse returns the Response field value
func (o *TableWebhookTestCallResponse) GetResponse() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Response
}

// GetResponseOk returns a tuple with the Response field value
// and a boolean to check if the value has been set.
func (o *TableWebhookTestCallResponse) GetResponseOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Response, true
}

// SetResponse sets field value
func (o *TableWebhookTestCallResponse) SetResponse(v string) {
	o.Response = v
}

// GetStatusCode returns the StatusCode field value
func (o *TableWebhookTestCallResponse) GetStatusCode() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.StatusCode
}

// GetStatusCodeOk returns a tuple with the StatusCode field value
// and a boolean to check if the value has been set.
func (o *TableWebhookTestCallResponse) GetStatusCodeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StatusCode, true
}

// SetStatusCode sets field value
func (o *TableWebhookTestCallResponse) SetStatusCode(v int32) {
	o.StatusCode = v
}

// GetIsUnreachable returns the IsUnreachable field value
func (o *TableWebhookTestCallResponse) GetIsUnreachable() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsUnreachable
}

// GetIsUnreachableOk returns a tuple with the IsUnreachable field value
// and a boolean to check if the value has been set.
func (o *TableWebhookTestCallResponse) GetIsUnreachableOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsUnreachable, true
}

// SetIsUnreachable sets field value
func (o *TableWebhookTestCallResponse) SetIsUnreachable(v bool) {
	o.IsUnreachable = v
}

func (o TableWebhookTestCallResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TableWebhookTestCallResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	// skip: request is readOnly
	// skip: response is readOnly
	// skip: status_code is readOnly
	// skip: is_unreachable is readOnly
	return toSerialize, nil
}

type NullableTableWebhookTestCallResponse struct {
	value *TableWebhookTestCallResponse
	isSet bool
}

func (v NullableTableWebhookTestCallResponse) Get() *TableWebhookTestCallResponse {
	return v.value
}

func (v *NullableTableWebhookTestCallResponse) Set(val *TableWebhookTestCallResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableTableWebhookTestCallResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableTableWebhookTestCallResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTableWebhookTestCallResponse(val *TableWebhookTestCallResponse) *NullableTableWebhookTestCallResponse {
	return &NullableTableWebhookTestCallResponse{value: val, isSet: true}
}

func (v NullableTableWebhookTestCallResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTableWebhookTestCallResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


