/*
Baserow API spec

For more information about our REST API, please visit [this page](https://baserow.io/docs/apis%2Frest-api).  For more information about our deprecation policy, please visit [this page](https://baserow.io/docs/apis%2Fdeprecations).

API version: 1.18.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the RequestDuplicateApplicationJobCreateJob type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RequestDuplicateApplicationJobCreateJob{}

// RequestDuplicateApplicationJobCreateJob struct for RequestDuplicateApplicationJobCreateJob
type RequestDuplicateApplicationJobCreateJob struct {
	Type Type4afEnum `json:"type"`
	// The application ID to duplicate.
	ApplicationId int32 `json:"application_id"`
}

// NewRequestDuplicateApplicationJobCreateJob instantiates a new RequestDuplicateApplicationJobCreateJob object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRequestDuplicateApplicationJobCreateJob(type_ Type4afEnum, applicationId int32) *RequestDuplicateApplicationJobCreateJob {
	this := RequestDuplicateApplicationJobCreateJob{}
	this.Type = type_
	this.ApplicationId = applicationId
	return &this
}

// NewRequestDuplicateApplicationJobCreateJobWithDefaults instantiates a new RequestDuplicateApplicationJobCreateJob object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRequestDuplicateApplicationJobCreateJobWithDefaults() *RequestDuplicateApplicationJobCreateJob {
	this := RequestDuplicateApplicationJobCreateJob{}
	return &this
}

// GetType returns the Type field value
func (o *RequestDuplicateApplicationJobCreateJob) GetType() Type4afEnum {
	if o == nil {
		var ret Type4afEnum
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *RequestDuplicateApplicationJobCreateJob) GetTypeOk() (*Type4afEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *RequestDuplicateApplicationJobCreateJob) SetType(v Type4afEnum) {
	o.Type = v
}

// GetApplicationId returns the ApplicationId field value
func (o *RequestDuplicateApplicationJobCreateJob) GetApplicationId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ApplicationId
}

// GetApplicationIdOk returns a tuple with the ApplicationId field value
// and a boolean to check if the value has been set.
func (o *RequestDuplicateApplicationJobCreateJob) GetApplicationIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ApplicationId, true
}

// SetApplicationId sets field value
func (o *RequestDuplicateApplicationJobCreateJob) SetApplicationId(v int32) {
	o.ApplicationId = v
}

func (o RequestDuplicateApplicationJobCreateJob) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RequestDuplicateApplicationJobCreateJob) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["application_id"] = o.ApplicationId
	return toSerialize, nil
}

type NullableRequestDuplicateApplicationJobCreateJob struct {
	value *RequestDuplicateApplicationJobCreateJob
	isSet bool
}

func (v NullableRequestDuplicateApplicationJobCreateJob) Get() *RequestDuplicateApplicationJobCreateJob {
	return v.value
}

func (v *NullableRequestDuplicateApplicationJobCreateJob) Set(val *RequestDuplicateApplicationJobCreateJob) {
	v.value = val
	v.isSet = true
}

func (v NullableRequestDuplicateApplicationJobCreateJob) IsSet() bool {
	return v.isSet
}

func (v *NullableRequestDuplicateApplicationJobCreateJob) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRequestDuplicateApplicationJobCreateJob(val *RequestDuplicateApplicationJobCreateJob) *NullableRequestDuplicateApplicationJobCreateJob {
	return &NullableRequestDuplicateApplicationJobCreateJob{value: val, isSet: true}
}

func (v NullableRequestDuplicateApplicationJobCreateJob) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRequestDuplicateApplicationJobCreateJob) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


