/*
Baserow API spec

For more information about our REST API, please visit [this page](https://baserow.io/docs/apis%2Frest-api).  For more information about our deprecation policy, please visit [this page](https://baserow.io/docs/apis%2Fdeprecations).

API version: 1.18.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the AdminImpersonateUser200ResponseUser type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AdminImpersonateUser200ResponseUser{}

// AdminImpersonateUser200ResponseUser An object containing information related to the user.
type AdminImpersonateUser200ResponseUser struct {
	// The first name of related user.
	FirstName *string `json:"first_name,omitempty"`
	// The username of the related user. This is always an email address.
	Username *string `json:"username,omitempty"`
	// An ISO 639 language code (with optional variant) selected by the user. Ex: en-GB.
	Language *string `json:"language,omitempty"`
}

// NewAdminImpersonateUser200ResponseUser instantiates a new AdminImpersonateUser200ResponseUser object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAdminImpersonateUser200ResponseUser() *AdminImpersonateUser200ResponseUser {
	this := AdminImpersonateUser200ResponseUser{}
	return &this
}

// NewAdminImpersonateUser200ResponseUserWithDefaults instantiates a new AdminImpersonateUser200ResponseUser object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAdminImpersonateUser200ResponseUserWithDefaults() *AdminImpersonateUser200ResponseUser {
	this := AdminImpersonateUser200ResponseUser{}
	return &this
}

// GetFirstName returns the FirstName field value if set, zero value otherwise.
func (o *AdminImpersonateUser200ResponseUser) GetFirstName() string {
	if o == nil || IsNil(o.FirstName) {
		var ret string
		return ret
	}
	return *o.FirstName
}

// GetFirstNameOk returns a tuple with the FirstName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminImpersonateUser200ResponseUser) GetFirstNameOk() (*string, bool) {
	if o == nil || IsNil(o.FirstName) {
		return nil, false
	}
	return o.FirstName, true
}

// HasFirstName returns a boolean if a field has been set.
func (o *AdminImpersonateUser200ResponseUser) HasFirstName() bool {
	if o != nil && !IsNil(o.FirstName) {
		return true
	}

	return false
}

// SetFirstName gets a reference to the given string and assigns it to the FirstName field.
func (o *AdminImpersonateUser200ResponseUser) SetFirstName(v string) {
	o.FirstName = &v
}

// GetUsername returns the Username field value if set, zero value otherwise.
func (o *AdminImpersonateUser200ResponseUser) GetUsername() string {
	if o == nil || IsNil(o.Username) {
		var ret string
		return ret
	}
	return *o.Username
}

// GetUsernameOk returns a tuple with the Username field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminImpersonateUser200ResponseUser) GetUsernameOk() (*string, bool) {
	if o == nil || IsNil(o.Username) {
		return nil, false
	}
	return o.Username, true
}

// HasUsername returns a boolean if a field has been set.
func (o *AdminImpersonateUser200ResponseUser) HasUsername() bool {
	if o != nil && !IsNil(o.Username) {
		return true
	}

	return false
}

// SetUsername gets a reference to the given string and assigns it to the Username field.
func (o *AdminImpersonateUser200ResponseUser) SetUsername(v string) {
	o.Username = &v
}

// GetLanguage returns the Language field value if set, zero value otherwise.
func (o *AdminImpersonateUser200ResponseUser) GetLanguage() string {
	if o == nil || IsNil(o.Language) {
		var ret string
		return ret
	}
	return *o.Language
}

// GetLanguageOk returns a tuple with the Language field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminImpersonateUser200ResponseUser) GetLanguageOk() (*string, bool) {
	if o == nil || IsNil(o.Language) {
		return nil, false
	}
	return o.Language, true
}

// HasLanguage returns a boolean if a field has been set.
func (o *AdminImpersonateUser200ResponseUser) HasLanguage() bool {
	if o != nil && !IsNil(o.Language) {
		return true
	}

	return false
}

// SetLanguage gets a reference to the given string and assigns it to the Language field.
func (o *AdminImpersonateUser200ResponseUser) SetLanguage(v string) {
	o.Language = &v
}

func (o AdminImpersonateUser200ResponseUser) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AdminImpersonateUser200ResponseUser) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.FirstName) {
		toSerialize["first_name"] = o.FirstName
	}
	if !IsNil(o.Username) {
		toSerialize["username"] = o.Username
	}
	if !IsNil(o.Language) {
		toSerialize["language"] = o.Language
	}
	return toSerialize, nil
}

type NullableAdminImpersonateUser200ResponseUser struct {
	value *AdminImpersonateUser200ResponseUser
	isSet bool
}

func (v NullableAdminImpersonateUser200ResponseUser) Get() *AdminImpersonateUser200ResponseUser {
	return v.value
}

func (v *NullableAdminImpersonateUser200ResponseUser) Set(val *AdminImpersonateUser200ResponseUser) {
	v.value = val
	v.isSet = true
}

func (v NullableAdminImpersonateUser200ResponseUser) IsSet() bool {
	return v.isSet
}

func (v *NullableAdminImpersonateUser200ResponseUser) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAdminImpersonateUser200ResponseUser(val *AdminImpersonateUser200ResponseUser) *NullableAdminImpersonateUser200ResponseUser {
	return &NullableAdminImpersonateUser200ResponseUser{value: val, isSet: true}
}

func (v NullableAdminImpersonateUser200ResponseUser) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAdminImpersonateUser200ResponseUser) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


