/*
Baserow API spec

For more information about our REST API, please visit [this page](https://baserow.io/docs/apis%2Frest-api).  For more information about our deprecation policy, please visit [this page](https://baserow.io/docs/apis%2Fdeprecations).

API version: 1.18.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the RequestRestoreSnapshotJobCreateJob type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RequestRestoreSnapshotJobCreateJob{}

// RequestRestoreSnapshotJobCreateJob struct for RequestRestoreSnapshotJobCreateJob
type RequestRestoreSnapshotJobCreateJob struct {
	Type Type4afEnum `json:"type"`
}

// NewRequestRestoreSnapshotJobCreateJob instantiates a new RequestRestoreSnapshotJobCreateJob object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRequestRestoreSnapshotJobCreateJob(type_ Type4afEnum) *RequestRestoreSnapshotJobCreateJob {
	this := RequestRestoreSnapshotJobCreateJob{}
	this.Type = type_
	return &this
}

// NewRequestRestoreSnapshotJobCreateJobWithDefaults instantiates a new RequestRestoreSnapshotJobCreateJob object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRequestRestoreSnapshotJobCreateJobWithDefaults() *RequestRestoreSnapshotJobCreateJob {
	this := RequestRestoreSnapshotJobCreateJob{}
	return &this
}

// GetType returns the Type field value
func (o *RequestRestoreSnapshotJobCreateJob) GetType() Type4afEnum {
	if o == nil {
		var ret Type4afEnum
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *RequestRestoreSnapshotJobCreateJob) GetTypeOk() (*Type4afEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *RequestRestoreSnapshotJobCreateJob) SetType(v Type4afEnum) {
	o.Type = v
}

func (o RequestRestoreSnapshotJobCreateJob) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RequestRestoreSnapshotJobCreateJob) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

type NullableRequestRestoreSnapshotJobCreateJob struct {
	value *RequestRestoreSnapshotJobCreateJob
	isSet bool
}

func (v NullableRequestRestoreSnapshotJobCreateJob) Get() *RequestRestoreSnapshotJobCreateJob {
	return v.value
}

func (v *NullableRequestRestoreSnapshotJobCreateJob) Set(val *RequestRestoreSnapshotJobCreateJob) {
	v.value = val
	v.isSet = true
}

func (v NullableRequestRestoreSnapshotJobCreateJob) IsSet() bool {
	return v.isSet
}

func (v *NullableRequestRestoreSnapshotJobCreateJob) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRequestRestoreSnapshotJobCreateJob(val *RequestRestoreSnapshotJobCreateJob) *NullableRequestRestoreSnapshotJobCreateJob {
	return &NullableRequestRestoreSnapshotJobCreateJob{value: val, isSet: true}
}

func (v NullableRequestRestoreSnapshotJobCreateJob) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRequestRestoreSnapshotJobCreateJob) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


