/*
Baserow API spec

For more information about our REST API, please visit [this page](https://baserow.io/docs/apis%2Frest-api).  For more information about our deprecation policy, please visit [this page](https://baserow.io/docs/apis%2Fdeprecations).

API version: 1.18.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"time"
)

// checks if the RequestAuditLogExportJobCreateJob type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RequestAuditLogExportJobCreateJob{}

// RequestAuditLogExportJobCreateJob struct for RequestAuditLogExportJobCreateJob
type RequestAuditLogExportJobCreateJob struct {
	Type Type4afEnum `json:"type"`
	ExportCharset *ExportCharsetEnum `json:"export_charset,omitempty"`
	CsvColumnSeparator *CsvColumnSeparatorEnum `json:"csv_column_separator,omitempty"`
	// Whether or not to generate a header row at the top of the csv file.
	CsvFirstRowHeader *bool `json:"csv_first_row_header,omitempty"`
	// Optional: The user to filter the audit log by.
	FilterUserId *int32 `json:"filter_user_id,omitempty"`
	// Optional: The workspace to filter the audit log by.
	FilterWorkspaceId *int32 `json:"filter_workspace_id,omitempty"`
	FilterActionType *FilterActionTypeEnum `json:"filter_action_type,omitempty"`
	// Optional: The start date to filter the audit log by.
	FilterFromTimestamp *time.Time `json:"filter_from_timestamp,omitempty"`
	// Optional: The end date to filter the audit log by.
	FilterToTimestamp *time.Time `json:"filter_to_timestamp,omitempty"`
	// The date and time when the export job was created.
	CreatedOn time.Time `json:"created_on"`
}

// NewRequestAuditLogExportJobCreateJob instantiates a new RequestAuditLogExportJobCreateJob object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRequestAuditLogExportJobCreateJob(type_ Type4afEnum, createdOn time.Time) *RequestAuditLogExportJobCreateJob {
	this := RequestAuditLogExportJobCreateJob{}
	this.Type = type_
	var exportCharset ExportCharsetEnum = UTF_8
	this.ExportCharset = &exportCharset
	var csvColumnSeparator CsvColumnSeparatorEnum = COMMA
	this.CsvColumnSeparator = &csvColumnSeparator
	var csvFirstRowHeader bool = true
	this.CsvFirstRowHeader = &csvFirstRowHeader
	this.CreatedOn = createdOn
	return &this
}

// NewRequestAuditLogExportJobCreateJobWithDefaults instantiates a new RequestAuditLogExportJobCreateJob object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRequestAuditLogExportJobCreateJobWithDefaults() *RequestAuditLogExportJobCreateJob {
	this := RequestAuditLogExportJobCreateJob{}
	var exportCharset ExportCharsetEnum = UTF_8
	this.ExportCharset = &exportCharset
	var csvColumnSeparator CsvColumnSeparatorEnum = COMMA
	this.CsvColumnSeparator = &csvColumnSeparator
	var csvFirstRowHeader bool = true
	this.CsvFirstRowHeader = &csvFirstRowHeader
	return &this
}

// GetType returns the Type field value
func (o *RequestAuditLogExportJobCreateJob) GetType() Type4afEnum {
	if o == nil {
		var ret Type4afEnum
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *RequestAuditLogExportJobCreateJob) GetTypeOk() (*Type4afEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *RequestAuditLogExportJobCreateJob) SetType(v Type4afEnum) {
	o.Type = v
}

// GetExportCharset returns the ExportCharset field value if set, zero value otherwise.
func (o *RequestAuditLogExportJobCreateJob) GetExportCharset() ExportCharsetEnum {
	if o == nil || IsNil(o.ExportCharset) {
		var ret ExportCharsetEnum
		return ret
	}
	return *o.ExportCharset
}

// GetExportCharsetOk returns a tuple with the ExportCharset field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RequestAuditLogExportJobCreateJob) GetExportCharsetOk() (*ExportCharsetEnum, bool) {
	if o == nil || IsNil(o.ExportCharset) {
		return nil, false
	}
	return o.ExportCharset, true
}

// HasExportCharset returns a boolean if a field has been set.
func (o *RequestAuditLogExportJobCreateJob) HasExportCharset() bool {
	if o != nil && !IsNil(o.ExportCharset) {
		return true
	}

	return false
}

// SetExportCharset gets a reference to the given ExportCharsetEnum and assigns it to the ExportCharset field.
func (o *RequestAuditLogExportJobCreateJob) SetExportCharset(v ExportCharsetEnum) {
	o.ExportCharset = &v
}

// GetCsvColumnSeparator returns the CsvColumnSeparator field value if set, zero value otherwise.
func (o *RequestAuditLogExportJobCreateJob) GetCsvColumnSeparator() CsvColumnSeparatorEnum {
	if o == nil || IsNil(o.CsvColumnSeparator) {
		var ret CsvColumnSeparatorEnum
		return ret
	}
	return *o.CsvColumnSeparator
}

// GetCsvColumnSeparatorOk returns a tuple with the CsvColumnSeparator field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RequestAuditLogExportJobCreateJob) GetCsvColumnSeparatorOk() (*CsvColumnSeparatorEnum, bool) {
	if o == nil || IsNil(o.CsvColumnSeparator) {
		return nil, false
	}
	return o.CsvColumnSeparator, true
}

// HasCsvColumnSeparator returns a boolean if a field has been set.
func (o *RequestAuditLogExportJobCreateJob) HasCsvColumnSeparator() bool {
	if o != nil && !IsNil(o.CsvColumnSeparator) {
		return true
	}

	return false
}

// SetCsvColumnSeparator gets a reference to the given CsvColumnSeparatorEnum and assigns it to the CsvColumnSeparator field.
func (o *RequestAuditLogExportJobCreateJob) SetCsvColumnSeparator(v CsvColumnSeparatorEnum) {
	o.CsvColumnSeparator = &v
}

// GetCsvFirstRowHeader returns the CsvFirstRowHeader field value if set, zero value otherwise.
func (o *RequestAuditLogExportJobCreateJob) GetCsvFirstRowHeader() bool {
	if o == nil || IsNil(o.CsvFirstRowHeader) {
		var ret bool
		return ret
	}
	return *o.CsvFirstRowHeader
}

// GetCsvFirstRowHeaderOk returns a tuple with the CsvFirstRowHeader field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RequestAuditLogExportJobCreateJob) GetCsvFirstRowHeaderOk() (*bool, bool) {
	if o == nil || IsNil(o.CsvFirstRowHeader) {
		return nil, false
	}
	return o.CsvFirstRowHeader, true
}

// HasCsvFirstRowHeader returns a boolean if a field has been set.
func (o *RequestAuditLogExportJobCreateJob) HasCsvFirstRowHeader() bool {
	if o != nil && !IsNil(o.CsvFirstRowHeader) {
		return true
	}

	return false
}

// SetCsvFirstRowHeader gets a reference to the given bool and assigns it to the CsvFirstRowHeader field.
func (o *RequestAuditLogExportJobCreateJob) SetCsvFirstRowHeader(v bool) {
	o.CsvFirstRowHeader = &v
}

// GetFilterUserId returns the FilterUserId field value if set, zero value otherwise.
func (o *RequestAuditLogExportJobCreateJob) GetFilterUserId() int32 {
	if o == nil || IsNil(o.FilterUserId) {
		var ret int32
		return ret
	}
	return *o.FilterUserId
}

// GetFilterUserIdOk returns a tuple with the FilterUserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RequestAuditLogExportJobCreateJob) GetFilterUserIdOk() (*int32, bool) {
	if o == nil || IsNil(o.FilterUserId) {
		return nil, false
	}
	return o.FilterUserId, true
}

// HasFilterUserId returns a boolean if a field has been set.
func (o *RequestAuditLogExportJobCreateJob) HasFilterUserId() bool {
	if o != nil && !IsNil(o.FilterUserId) {
		return true
	}

	return false
}

// SetFilterUserId gets a reference to the given int32 and assigns it to the FilterUserId field.
func (o *RequestAuditLogExportJobCreateJob) SetFilterUserId(v int32) {
	o.FilterUserId = &v
}

// GetFilterWorkspaceId returns the FilterWorkspaceId field value if set, zero value otherwise.
func (o *RequestAuditLogExportJobCreateJob) GetFilterWorkspaceId() int32 {
	if o == nil || IsNil(o.FilterWorkspaceId) {
		var ret int32
		return ret
	}
	return *o.FilterWorkspaceId
}

// GetFilterWorkspaceIdOk returns a tuple with the FilterWorkspaceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RequestAuditLogExportJobCreateJob) GetFilterWorkspaceIdOk() (*int32, bool) {
	if o == nil || IsNil(o.FilterWorkspaceId) {
		return nil, false
	}
	return o.FilterWorkspaceId, true
}

// HasFilterWorkspaceId returns a boolean if a field has been set.
func (o *RequestAuditLogExportJobCreateJob) HasFilterWorkspaceId() bool {
	if o != nil && !IsNil(o.FilterWorkspaceId) {
		return true
	}

	return false
}

// SetFilterWorkspaceId gets a reference to the given int32 and assigns it to the FilterWorkspaceId field.
func (o *RequestAuditLogExportJobCreateJob) SetFilterWorkspaceId(v int32) {
	o.FilterWorkspaceId = &v
}

// GetFilterActionType returns the FilterActionType field value if set, zero value otherwise.
func (o *RequestAuditLogExportJobCreateJob) GetFilterActionType() FilterActionTypeEnum {
	if o == nil || IsNil(o.FilterActionType) {
		var ret FilterActionTypeEnum
		return ret
	}
	return *o.FilterActionType
}

// GetFilterActionTypeOk returns a tuple with the FilterActionType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RequestAuditLogExportJobCreateJob) GetFilterActionTypeOk() (*FilterActionTypeEnum, bool) {
	if o == nil || IsNil(o.FilterActionType) {
		return nil, false
	}
	return o.FilterActionType, true
}

// HasFilterActionType returns a boolean if a field has been set.
func (o *RequestAuditLogExportJobCreateJob) HasFilterActionType() bool {
	if o != nil && !IsNil(o.FilterActionType) {
		return true
	}

	return false
}

// SetFilterActionType gets a reference to the given FilterActionTypeEnum and assigns it to the FilterActionType field.
func (o *RequestAuditLogExportJobCreateJob) SetFilterActionType(v FilterActionTypeEnum) {
	o.FilterActionType = &v
}

// GetFilterFromTimestamp returns the FilterFromTimestamp field value if set, zero value otherwise.
func (o *RequestAuditLogExportJobCreateJob) GetFilterFromTimestamp() time.Time {
	if o == nil || IsNil(o.FilterFromTimestamp) {
		var ret time.Time
		return ret
	}
	return *o.FilterFromTimestamp
}

// GetFilterFromTimestampOk returns a tuple with the FilterFromTimestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RequestAuditLogExportJobCreateJob) GetFilterFromTimestampOk() (*time.Time, bool) {
	if o == nil || IsNil(o.FilterFromTimestamp) {
		return nil, false
	}
	return o.FilterFromTimestamp, true
}

// HasFilterFromTimestamp returns a boolean if a field has been set.
func (o *RequestAuditLogExportJobCreateJob) HasFilterFromTimestamp() bool {
	if o != nil && !IsNil(o.FilterFromTimestamp) {
		return true
	}

	return false
}

// SetFilterFromTimestamp gets a reference to the given time.Time and assigns it to the FilterFromTimestamp field.
func (o *RequestAuditLogExportJobCreateJob) SetFilterFromTimestamp(v time.Time) {
	o.FilterFromTimestamp = &v
}

// GetFilterToTimestamp returns the FilterToTimestamp field value if set, zero value otherwise.
func (o *RequestAuditLogExportJobCreateJob) GetFilterToTimestamp() time.Time {
	if o == nil || IsNil(o.FilterToTimestamp) {
		var ret time.Time
		return ret
	}
	return *o.FilterToTimestamp
}

// GetFilterToTimestampOk returns a tuple with the FilterToTimestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RequestAuditLogExportJobCreateJob) GetFilterToTimestampOk() (*time.Time, bool) {
	if o == nil || IsNil(o.FilterToTimestamp) {
		return nil, false
	}
	return o.FilterToTimestamp, true
}

// HasFilterToTimestamp returns a boolean if a field has been set.
func (o *RequestAuditLogExportJobCreateJob) HasFilterToTimestamp() bool {
	if o != nil && !IsNil(o.FilterToTimestamp) {
		return true
	}

	return false
}

// SetFilterToTimestamp gets a reference to the given time.Time and assigns it to the FilterToTimestamp field.
func (o *RequestAuditLogExportJobCreateJob) SetFilterToTimestamp(v time.Time) {
	o.FilterToTimestamp = &v
}

// GetCreatedOn returns the CreatedOn field value
func (o *RequestAuditLogExportJobCreateJob) GetCreatedOn() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedOn
}

// GetCreatedOnOk returns a tuple with the CreatedOn field value
// and a boolean to check if the value has been set.
func (o *RequestAuditLogExportJobCreateJob) GetCreatedOnOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedOn, true
}

// SetCreatedOn sets field value
func (o *RequestAuditLogExportJobCreateJob) SetCreatedOn(v time.Time) {
	o.CreatedOn = v
}

func (o RequestAuditLogExportJobCreateJob) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RequestAuditLogExportJobCreateJob) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	if !IsNil(o.ExportCharset) {
		toSerialize["export_charset"] = o.ExportCharset
	}
	if !IsNil(o.CsvColumnSeparator) {
		toSerialize["csv_column_separator"] = o.CsvColumnSeparator
	}
	if !IsNil(o.CsvFirstRowHeader) {
		toSerialize["csv_first_row_header"] = o.CsvFirstRowHeader
	}
	if !IsNil(o.FilterUserId) {
		toSerialize["filter_user_id"] = o.FilterUserId
	}
	if !IsNil(o.FilterWorkspaceId) {
		toSerialize["filter_workspace_id"] = o.FilterWorkspaceId
	}
	if !IsNil(o.FilterActionType) {
		toSerialize["filter_action_type"] = o.FilterActionType
	}
	if !IsNil(o.FilterFromTimestamp) {
		toSerialize["filter_from_timestamp"] = o.FilterFromTimestamp
	}
	if !IsNil(o.FilterToTimestamp) {
		toSerialize["filter_to_timestamp"] = o.FilterToTimestamp
	}
	// skip: created_on is readOnly
	return toSerialize, nil
}

type NullableRequestAuditLogExportJobCreateJob struct {
	value *RequestAuditLogExportJobCreateJob
	isSet bool
}

func (v NullableRequestAuditLogExportJobCreateJob) Get() *RequestAuditLogExportJobCreateJob {
	return v.value
}

func (v *NullableRequestAuditLogExportJobCreateJob) Set(val *RequestAuditLogExportJobCreateJob) {
	v.value = val
	v.isSet = true
}

func (v NullableRequestAuditLogExportJobCreateJob) IsSet() bool {
	return v.isSet
}

func (v *NullableRequestAuditLogExportJobCreateJob) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRequestAuditLogExportJobCreateJob(val *RequestAuditLogExportJobCreateJob) *NullableRequestAuditLogExportJobCreateJob {
	return &NullableRequestAuditLogExportJobCreateJob{value: val, isSet: true}
}

func (v NullableRequestAuditLogExportJobCreateJob) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRequestAuditLogExportJobCreateJob) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


