/*
Baserow API spec

For more information about our REST API, please visit [this page](https://baserow.io/docs/apis%2Frest-api).  For more information about our deprecation policy, please visit [this page](https://baserow.io/docs/apis%2Fdeprecations).

API version: 1.18.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the PaginationSerializerLinkRowValue type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaginationSerializerLinkRowValue{}

// PaginationSerializerLinkRowValue struct for PaginationSerializerLinkRowValue
type PaginationSerializerLinkRowValue struct {
	// The total amount of results.
	Count int32 `json:"count"`
	// URL to the next page.
	Next NullableString `json:"next"`
	// URL to the previous page.
	Previous NullableString `json:"previous"`
	Results []LinkRowValue `json:"results"`
}

// NewPaginationSerializerLinkRowValue instantiates a new PaginationSerializerLinkRowValue object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaginationSerializerLinkRowValue(count int32, next NullableString, previous NullableString, results []LinkRowValue) *PaginationSerializerLinkRowValue {
	this := PaginationSerializerLinkRowValue{}
	this.Count = count
	this.Next = next
	this.Previous = previous
	this.Results = results
	return &this
}

// NewPaginationSerializerLinkRowValueWithDefaults instantiates a new PaginationSerializerLinkRowValue object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaginationSerializerLinkRowValueWithDefaults() *PaginationSerializerLinkRowValue {
	this := PaginationSerializerLinkRowValue{}
	return &this
}

// GetCount returns the Count field value
func (o *PaginationSerializerLinkRowValue) GetCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Count
}

// GetCountOk returns a tuple with the Count field value
// and a boolean to check if the value has been set.
func (o *PaginationSerializerLinkRowValue) GetCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Count, true
}

// SetCount sets field value
func (o *PaginationSerializerLinkRowValue) SetCount(v int32) {
	o.Count = v
}

// GetNext returns the Next field value
// If the value is explicit nil, the zero value for string will be returned
func (o *PaginationSerializerLinkRowValue) GetNext() string {
	if o == nil || o.Next.Get() == nil {
		var ret string
		return ret
	}

	return *o.Next.Get()
}

// GetNextOk returns a tuple with the Next field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PaginationSerializerLinkRowValue) GetNextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Next.Get(), o.Next.IsSet()
}

// SetNext sets field value
func (o *PaginationSerializerLinkRowValue) SetNext(v string) {
	o.Next.Set(&v)
}

// GetPrevious returns the Previous field value
// If the value is explicit nil, the zero value for string will be returned
func (o *PaginationSerializerLinkRowValue) GetPrevious() string {
	if o == nil || o.Previous.Get() == nil {
		var ret string
		return ret
	}

	return *o.Previous.Get()
}

// GetPreviousOk returns a tuple with the Previous field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PaginationSerializerLinkRowValue) GetPreviousOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Previous.Get(), o.Previous.IsSet()
}

// SetPrevious sets field value
func (o *PaginationSerializerLinkRowValue) SetPrevious(v string) {
	o.Previous.Set(&v)
}

// GetResults returns the Results field value
func (o *PaginationSerializerLinkRowValue) GetResults() []LinkRowValue {
	if o == nil {
		var ret []LinkRowValue
		return ret
	}

	return o.Results
}

// GetResultsOk returns a tuple with the Results field value
// and a boolean to check if the value has been set.
func (o *PaginationSerializerLinkRowValue) GetResultsOk() ([]LinkRowValue, bool) {
	if o == nil {
		return nil, false
	}
	return o.Results, true
}

// SetResults sets field value
func (o *PaginationSerializerLinkRowValue) SetResults(v []LinkRowValue) {
	o.Results = v
}

func (o PaginationSerializerLinkRowValue) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaginationSerializerLinkRowValue) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["count"] = o.Count
	toSerialize["next"] = o.Next.Get()
	toSerialize["previous"] = o.Previous.Get()
	toSerialize["results"] = o.Results
	return toSerialize, nil
}

type NullablePaginationSerializerLinkRowValue struct {
	value *PaginationSerializerLinkRowValue
	isSet bool
}

func (v NullablePaginationSerializerLinkRowValue) Get() *PaginationSerializerLinkRowValue {
	return v.value
}

func (v *NullablePaginationSerializerLinkRowValue) Set(val *PaginationSerializerLinkRowValue) {
	v.value = val
	v.isSet = true
}

func (v NullablePaginationSerializerLinkRowValue) IsSet() bool {
	return v.isSet
}

func (v *NullablePaginationSerializerLinkRowValue) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaginationSerializerLinkRowValue(val *PaginationSerializerLinkRowValue) *NullablePaginationSerializerLinkRowValue {
	return &NullablePaginationSerializerLinkRowValue{value: val, isSet: true}
}

func (v NullablePaginationSerializerLinkRowValue) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaginationSerializerLinkRowValue) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


