/*
Baserow API spec

For more information about our REST API, please visit [this page](https://baserow.io/docs/apis%2Frest-api).  For more information about our deprecation policy, please visit [this page](https://baserow.io/docs/apis%2Fdeprecations).

API version: 1.18.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the PatchedUndoRedoRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PatchedUndoRedoRequest{}

// PatchedUndoRedoRequest struct for PatchedUndoRedoRequest
type PatchedUndoRedoRequest struct {
	Scopes *PatchedUndoRedoRequestScopes `json:"scopes,omitempty"`
}

// NewPatchedUndoRedoRequest instantiates a new PatchedUndoRedoRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPatchedUndoRedoRequest() *PatchedUndoRedoRequest {
	this := PatchedUndoRedoRequest{}
	return &this
}

// NewPatchedUndoRedoRequestWithDefaults instantiates a new PatchedUndoRedoRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPatchedUndoRedoRequestWithDefaults() *PatchedUndoRedoRequest {
	this := PatchedUndoRedoRequest{}
	return &this
}

// GetScopes returns the Scopes field value if set, zero value otherwise.
func (o *PatchedUndoRedoRequest) GetScopes() PatchedUndoRedoRequestScopes {
	if o == nil || IsNil(o.Scopes) {
		var ret PatchedUndoRedoRequestScopes
		return ret
	}
	return *o.Scopes
}

// GetScopesOk returns a tuple with the Scopes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedUndoRedoRequest) GetScopesOk() (*PatchedUndoRedoRequestScopes, bool) {
	if o == nil || IsNil(o.Scopes) {
		return nil, false
	}
	return o.Scopes, true
}

// HasScopes returns a boolean if a field has been set.
func (o *PatchedUndoRedoRequest) HasScopes() bool {
	if o != nil && !IsNil(o.Scopes) {
		return true
	}

	return false
}

// SetScopes gets a reference to the given PatchedUndoRedoRequestScopes and assigns it to the Scopes field.
func (o *PatchedUndoRedoRequest) SetScopes(v PatchedUndoRedoRequestScopes) {
	o.Scopes = &v
}

func (o PatchedUndoRedoRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PatchedUndoRedoRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Scopes) {
		toSerialize["scopes"] = o.Scopes
	}
	return toSerialize, nil
}

type NullablePatchedUndoRedoRequest struct {
	value *PatchedUndoRedoRequest
	isSet bool
}

func (v NullablePatchedUndoRedoRequest) Get() *PatchedUndoRedoRequest {
	return v.value
}

func (v *NullablePatchedUndoRedoRequest) Set(val *PatchedUndoRedoRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePatchedUndoRedoRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePatchedUndoRedoRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePatchedUndoRedoRequest(val *PatchedUndoRedoRequest) *NullablePatchedUndoRedoRequest {
	return &NullablePatchedUndoRedoRequest{value: val, isSet: true}
}

func (v NullablePatchedUndoRedoRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePatchedUndoRedoRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


