/*
Baserow API spec

For more information about our REST API, please visit [this page](https://baserow.io/docs/apis%2Frest-api).  For more information about our deprecation policy, please visit [this page](https://baserow.io/docs/apis%2Fdeprecations).

API version: 1.18.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the RequestDuplicateTableJobCreateJob type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RequestDuplicateTableJobCreateJob{}

// RequestDuplicateTableJobCreateJob struct for RequestDuplicateTableJobCreateJob
type RequestDuplicateTableJobCreateJob struct {
	Type Type4afEnum `json:"type"`
	// The ID of the table to duplicate.
	TableId int32 `json:"table_id"`
}

// NewRequestDuplicateTableJobCreateJob instantiates a new RequestDuplicateTableJobCreateJob object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRequestDuplicateTableJobCreateJob(type_ Type4afEnum, tableId int32) *RequestDuplicateTableJobCreateJob {
	this := RequestDuplicateTableJobCreateJob{}
	this.Type = type_
	this.TableId = tableId
	return &this
}

// NewRequestDuplicateTableJobCreateJobWithDefaults instantiates a new RequestDuplicateTableJobCreateJob object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRequestDuplicateTableJobCreateJobWithDefaults() *RequestDuplicateTableJobCreateJob {
	this := RequestDuplicateTableJobCreateJob{}
	return &this
}

// GetType returns the Type field value
func (o *RequestDuplicateTableJobCreateJob) GetType() Type4afEnum {
	if o == nil {
		var ret Type4afEnum
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *RequestDuplicateTableJobCreateJob) GetTypeOk() (*Type4afEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *RequestDuplicateTableJobCreateJob) SetType(v Type4afEnum) {
	o.Type = v
}

// GetTableId returns the TableId field value
func (o *RequestDuplicateTableJobCreateJob) GetTableId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TableId
}

// GetTableIdOk returns a tuple with the TableId field value
// and a boolean to check if the value has been set.
func (o *RequestDuplicateTableJobCreateJob) GetTableIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TableId, true
}

// SetTableId sets field value
func (o *RequestDuplicateTableJobCreateJob) SetTableId(v int32) {
	o.TableId = v
}

func (o RequestDuplicateTableJobCreateJob) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RequestDuplicateTableJobCreateJob) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["table_id"] = o.TableId
	return toSerialize, nil
}

type NullableRequestDuplicateTableJobCreateJob struct {
	value *RequestDuplicateTableJobCreateJob
	isSet bool
}

func (v NullableRequestDuplicateTableJobCreateJob) Get() *RequestDuplicateTableJobCreateJob {
	return v.value
}

func (v *NullableRequestDuplicateTableJobCreateJob) Set(val *RequestDuplicateTableJobCreateJob) {
	v.value = val
	v.isSet = true
}

func (v NullableRequestDuplicateTableJobCreateJob) IsSet() bool {
	return v.isSet
}

func (v *NullableRequestDuplicateTableJobCreateJob) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRequestDuplicateTableJobCreateJob(val *RequestDuplicateTableJobCreateJob) *NullableRequestDuplicateTableJobCreateJob {
	return &NullableRequestDuplicateTableJobCreateJob{value: val, isSet: true}
}

func (v NullableRequestDuplicateTableJobCreateJob) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRequestDuplicateTableJobCreateJob) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


