apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "modware-import.fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  template:
    metadata:
      name: {{ template "modware-import.fullname" . }}
      labels:
        app: {{ template "modware-import.fullname" . }}
    spec:
      containers:
      {{- range $loader := .Values.load }}
      {{- if eq $loader.command "stockcenter" }}
      - name: {{ randAlpha 10 | printf "%s-%s-%s" $.Release.Name "plasmid" | trimSuffix "-" | lower }}
        image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag }}"
        imagePullPolicy: {{ $.Values.image.pullPolicy }}
        command: ["/usr/local/bin/plasmid-runner", {{ $loader.plasmid | join " " }}]
        env:
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
               name: dictybase-configuration
               key: minio.secretkey
        - name: ACCESS_KEY
          valueFrom:
            secretKeyRef:
               name: dictybase-configuration
               key: minio.accesskey
      - name: {{ randAlpha 10 | printf "%s-%s-%s" $.Release.Name "strain" | trimSuffix "-" | lower }}
        image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag }}"
        imagePullPolicy: "{{ $.Values.image.pullPolicy }}"
        command: ["/usr/local/bin/strain-runner", {{ $loader.strain | join " " }}]
        env:
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
               name: dictybase-configuration
               key: minio.secretkey
        - name: ACCESS_KEY
          valueFrom:
            secretKeyRef:
               name: dictybase-configuration
               key: minio.accesskey
      {{- end }}
      {{- end }}
      restartPolicy: Never
