apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "modware-import.fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  template:
    metadata:
      name: {{ template "modware-import.fullname" . }}
      labels:
        app: {{ template "modware-import.fullname" . }}
    spec:
      containers:
      {{- range $loader := .Values.load }}
      {{- if eq $loader.command "stockcenter" }}
      - name: {{ template "modware-import.containerName" $ }}
        {{- include "modware-import.imageManifest" $ | nindent 8 }}
        {{- include "modware-import.envManifest" $ | nindent 8 }}
        command: ["/usr/local/bin/dsc-runner"]
        args: [{{ $loader.subGroupOne | join "," }}]
      - name: {{ template "modware-import.containerName" $ }}
        {{- include "modware-import.imageManifest" $ | nindent 8 }}
        {{- include "modware-import.envManifest" $ | nindent 8 }}
        command: ["/usr/local/bin/dsc-runner"]
        args: [{{ $loader.subGroupTwo | join "," }}]
      - name: {{ template "modware-import.containerName" $ }}
        {{- include "modware-import.imageManifest" $ | nindent 8 }}
        {{- include "modware-import.envManifest" $ | nindent 8 }}
        command: ["/usr/local/bin/dsc-runner"]
        args: [{{ $loader.subGroupThree | join "," }}]
      restartPolicy: Never
