apiVersion: batch/v1
kind: Job
metadata:
  name: {{ printf "%s-%s-%s" (include "modware-import.fullname" .) "stockcenter" (randAlpha 8) | lower }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  template:
    metadata:
      name: {{ printf "%s-%s-%s" (include "modware-import.fullname" .) "stockcenter" (randAlpha 8) | lower }}
      labels:
        app: {{ printf "%s-%s" (include "modware-import.fullname" .)  "subGroupOne" }}
    spec:
      containers:
      - name: {{ template "modware-import.containerName" . }}
        {{- include "modware-import.imageManifest" . | nindent 8 }}
        {{- include "modware-import.envManifest" . | nindent 8 }}
        command: ["/usr/local/bin/dsc-runner"]
        args: [{{ .Values.load.stockcenter.subGroupOne | join "," }}]
      restartPolicy: Never
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ printf "%s-%s-%s" (include "modware-import.fullname" .) "stockcenter" (randAlpha 8) | lower }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  template:
    metadata:
      name: {{ printf "%s-%s-%s" (include "modware-import.fullname" .) "stockcenter" (randAlpha 8) | lower }}
      labels:
        app: {{ printf "%s-%s" (include "modware-import.fullname" .)  "subGroupTwo" }}
    spec:
      containers:
      - name: {{ template "modware-import.containerName" . }}
        {{- include "modware-import.imageManifest" . | nindent 8 }}
        {{- include "modware-import.envManifest" . | nindent 8 }}
        command: ["/usr/local/bin/dsc-runner"]
        args: [{{ .Values.load.stockcenter.subGroupTwo | join "," }}]
      restartPolicy: Never
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ printf "%s-%s-%s" (include "modware-import.fullname" .) "stockcenter" (randAlpha 8) | lower }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  template:
    metadata:
      name: {{ printf "%s-%s-%s" (include "modware-import.fullname" .) "stockcenter" (randAlpha 8) | lower }}
      labels:
        app: {{ printf "%s-%s" (include "modware-import.fullname" .)  "subGroupThree" }}
    spec:
      containers:
      - name: {{ template "modware-import.containerName" . }}
        {{- include "modware-import.imageManifest" . | nindent 8 }}
        {{- include "modware-import.envManifest" . | nindent 8 }}
        command: ["/usr/local/bin/dsc-runner"]
        args: [{{ .Values.load.stockcenter.subGroupThree | join "," }}]
      restartPolicy: Never

