version: "2"
run:
  allow-parallel-runners: true
linters:
  default: none
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - copyloopvar
    - cyclop
    - decorder
    - dogsled
    - funlen
    - funcorder
    - goconst
    - gocritic
    - gocyclo
    - gosec
    - govet
    - gocognit
    - ineffassign
    - importas
    - inamedparam
    - interfacebloat
    - lll
    - loggercheck
    - misspell
    - mnd
    - nakedret
    - nestif
    - revive
    - recvcheck
    - staticcheck
    - unconvert
    - usestdlibvars
    - unparam
    - unused
    - whitespace
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofumpt
    - goimports
    - golines
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
