package stockcenter

const (
	OrderClientKey           = "order-client"
	StockClientKey           = "stock-client"
	StockClient              = "stock"
	AnnotationClientKey      = "annotation-client"
	AnnotationClient         = "annotation"
	PlasmidIdMapReader       = "plasmid-id-map-input"
	PlasmidAnnotatorReader   = "plasmid-annotator-input"
	PlasmidPubReader         = "plasmid-pub-input"
	PlasmidGeneReader        = "plasmid-gene-input"
	PlasmidReader            = "plasmid-input"
	OrderReader              = "order-input"
	StrainReader             = "strain-input"
	StrainAnnotatorReader    = "strain-annotator-input"
	StrainPubReader          = "strain-pub-input"
	StrainGeneReader         = "strain-gene-input"
	StraincharReader         = "strain-char-input"
	PhenoReader              = "pheno-input"
	GenoReader               = "geno-input"
	StrainpropReader         = "strainprop-input"
	StrainSynReader          = "strainsyn-input"
	DefaultUser              = "dictybase@northwestern.edu"
	DictyAnnoOntology        = "dicty_annotation"
	DictyMutagenesisOntology = "Dd Mutagenesis Method"
	DictyGeneticmodOntology  = "genetic modification"
	DictyStraincharOntology  = "strain_characteristics"
	ReadfileReader           = "readfile-input"
	StockDateLayout          = "02-Jan-06"
	GwdiReader               = "gwdi-input"
)
