# Default values for arango-admin.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: dictybase/modware-import
  tag: latest
  pullPolicy: IfNotPresent

# data to be loaded
load:
  - command: stockcenter
    plasmid:
      - strain
      - plasmid
      - characteristics
    strain:
      - strain
      - characteristics
      #- name: order
  #- command: genome
    #group:
      #-



# verbosity of log
log:
  level: debug
