package manifest

type strSliceFnT func() []string

func Adjective() []string {
	adjective := make([]string, 0)
	for _, fn := range []strSliceFnT{adjectiveFour, adjectiveTwo, adjectiveOne, adjectiveThree} {
		adjective = append(adjective, fn()...)
	}

	return adjective
}

func adjectiveFour() []string {
	return []string{
		"Able", "Absent", "Absolute", "Abstract", "Absurd", "Academic",
		"Acceptable", "Accessible", "Accountable", "Accurate", "Acid", "Active",
		"Actual", "Acute", "Additional", "Adequate", "Adjacent",
		"Administrative", "Adult", "Advance", "Advanced", "Adverse",
		"Aesthetic", "Affordable", "Afraid", "Aged",
		"Agricultural", "Alert", "Alien", "Alike", "Alive",
		"Alone", "Alternative", "Amateur", "Amazed", "Amazing", "Ambitious",
		"Amusing", "Ancient", "Angry", "Annoyed", "Annoying", "Annual",
		"Anonymous", "Anxious", "Apparent", "Appealing", "Applicable",
		"Appropriate", "Arbitrary", "Architectural", "Artificial",
		"Artistic", "Ashamed", "Asleep", "Assistant", "Associated",
		"Astonishing", "Attractive", "Audio", "Authentic", "Automatic",
		"Available", "Average", "Aware", "Awful", "Awkward", "Back", "Bad",
		"Balanced", "Bare", "Based", "Basic", "Beautiful", "Beloved",
		"Beneficial", "Bent", "Best", "Better", "Big", "Biological", "Bitter",
		"Bizarre", "Blank", "Blind", "Blonde", "Blue", "Bold", "Bored",
		"Boring", "Bottom", "Bound", "Brave", "Brief", "Bright", "Brilliant",
		"Broad", "Broken", "Brown", "Busy", "Calm", "Capable",
		"Capital", "Capitalist", "Careful", "Careless", "Casual", "Cautious",
		"Central", "Certain", "Challenging", "Characteristic", "Charming",
		"Cheap", "Cheerful", "Chemical", "Chief", "Chronic", "Civic", "Civil",
		"Civilian", "Classic", "Classical", "Clean", "Clear", "Clever",
		"Clinical", "Close", "Closed", "Coastal", "Cognitive", "Cold",
		"Collective", "Colonial", "Coloured", "Colourful", "Comfortable",
		"Comic", "Commercial", "Common", "Communist", "Comparable",
		"Comparative", "Compelling", "Competent", "Competitive", "Complete",
		"Complex", "Complicated", "Comprehensive", "Compulsory", "Concerned",
		"Concrete", "Confident", "Confused", "Confusing", "Congressional",
		"Connected", "Conscious", "Consecutive", "Conservative", "Considerable",
		"Consistent", "Constant", "Constitutional", "Contemporary", "Content",
	}
}

func adjectiveThree() []string {
	return []string{
		"Continuous", "Contrary", "Controversial", "Convenient", "Conventional",
		"Convinced", "Convincing", "Cool", "Cooperative", "Core", "Corporate",
		"Correct", "Corresponding", "Costly", "Countless", "Covered",
		"Cream", "Creative", "Credible", "Critical",
		"Crowded", "Crucial", "Crude", "Cruel", "Cult", "Cultural", "Curious",
		"Curly", "Current", "Curved", "Cute", "Cynical", "Daily", "Dairy",
		"Damaging", "Dangerous", "Dark", "Dead", "Dear", "Decent",
		"Decisive", "Dedicated", "Deep", "Defensive", "Definite", "Deliberate",
		"Delicate", "Delicious", "Delighted", "Democratic", "Dense",
		"Dependent", "Depressed", "Depressing", "Desirable", "Desperate",
		"Destructive", "Detailed", "Determined", "Different", "Difficult",
		"Digital", "Diplomatic", "Direct", "Dirty", "Disabled", "Disappointed",
		"Disappointing", "Disastrous", "Dishonest", "Distant", "Distinct",
		"Distinctive", "Disturbing", "Diverse", "Divine", "Divorced",
		"Domestic", "Dominant", "Double", "Downstairs", "Downtown", "Dramatic",
		"Dressed", "Driving", "Dry", "Dual", "Due", "Dull", "Dumb",
		"Dynamic", "Eager", "Early", "East", "Eastern", "Easy", "Ecological",
		"Economic", "Editorial", "Educated", "Educational", "Effective",
		"Efficient", "Elaborate", "Elderly", "Electoral", "Electric",
		"Electrical", "Electronic", "Elegant", "Elementary", "Eligible",
		"Embarrassed", "Embarrassing", "Emotional", "Empirical", "Empty",
		"Encouraging", "Endless", "Engaged", "Engaging", "Enjoyable",
		"Enormous", "Entertaining", "Enthusiastic", "Entire", "Environmental",
		"Equal", "Equivalent", "Essential", "Eternal", "Ethical", "Ethnic",
		"Even", "Everyday", "Evident", "Evil", "Evolutionary", "Exact",
		"Excellent", "Exceptional", "Excess", "Excessive", "Excited",
		"Exciting", "Exclusive", "Executive", "Exotic", "Expected", "Expensive",
		"Experienced", "Experimental", "Expert", "Explicit", "Explosive",
		"Extensive", "External", "Extra", "Extraordinary", "Extreme",
		"Fabulous", "Failed", "Fair", "Fake", "False", "Familiar", "Family",
		"Famous", "Fancy", "Fantastic", "Far", "Fascinating", "Fashionable",
		"Fast", "Fat", "Fatal", "Favourable", "Favourite", "Federal", "Fellow",
		"Feminist", "Few", "Fierce", "Final", "Financial", "Fine",
		"Firm", "Fit", "Fixed", "Flat", "Flawed", "Flexible", "Flying",
		"Folding", "Folk", "Following", "Fond", "Foreign", "Formal", "Former",
		"Forthcoming", "Fortunate", "Forward", "Fragile", "Free", "Frequent",
		"Fresh", "Friendly", "Frightened", "Frightening", "Front", "Frozen",
		"Frustrated", "Frustrating", "Full", "FullTime", "Fun", "Functional",
		"Fundamental", "Funny", "Furious", "Further", "Future",
		"General", "Generic", "Generous", "Genetic", "Gentle", "Genuine",
	}
}

func adjectiveTwo() []string {
	return []string{
		"Giant", "Glad", "Global", "Glorious", "Gold", "Golden", "Good",
		"Gorgeous", "Grand", "Graphic", "Grateful", "Grave", "Great", "Green",
		"Grey", "Gross", "Guilty", "Handy", "Happy", "Hard", "Harmful", "Harsh",
		"Healthy", "Heavy", "Helpful", "Hidden", "High", "HighProfile",
		"Hilarious", "Historic", "Historical", "Hollow", "Holy", "Home",
		"Homeless", "Honest", "Hopeful", "Horrible", "Hot", "Huge",
		"Human", "Humanitarian", "Humble", "Humorous", "Hungry", "Hurt",
		"Ideal", "Identical", "Ideological", "Ill", "Illegal", "Imaginary",
		"Immediate", "Immense", "Imminent", "Immune", "Impatient", "Important",
		"Impossible", "Impressed", "Impressive", "Inadequate", "Inappropriate",
		"Inclined", "Included", "Incorrect", "Incredible", "Independent",
		"Indigenous", "Indirect", "Individual", "Indoor", "Industrial",
		"Inevitable", "Infamous", "Influential", "Informal", "Inherent",
		"Initial", "Injured", "Inner", "Innocent", "Innovative", "Inside",
		"Instant", "Institutional", "Instrumental", "Insufficient", "Intact",
		"Integral", "Integrated", "Intellectual", "Intelligent", "Intended",
		"Intense", "Intensive", "Interactive", "Interested", "Interesting",
		"Interim", "Interior", "Intermediate", "Internal", "International",
		"Intimate", "Intriguing", "Invisible", "Involved", "Ironic",
		"Irrelevant", "Isolated", "Joint", "Judicial", "Junior", "Just", "Keen",
		"Key", "Kind", "Large", "LargeScale", "Late", "Later", "Latest",
		"Latter", "Lazy", "Leading", "Left", "Legal", "Legendary",
		"Legislative", "Legitimate", "Lengthy", "Lesser",
		"Level", "Liable", "Liberal", "Lifelong", "Light", "Likely", "Limited",
		"Linear", "Liquid", "Literary", "Little", "Live", "Lively", "Living",
		"Local", "Located", "Logical", "Lonely", "Long", "LongStanding",
		"LongTerm", "LongTime", "Loose", "Lost", "Loud", "Lovely", "Low",
		"Loyal", "Lucky", "Luxury", "Mad", "Magic", "Magical", "Magnetic",
		"Magnificent", "Main", "Mainstream", "Major", "Mandatory",
		"Marginal", "Marine", "Married", "Martial", "Mass", "Massive",
		"Matching", "Material", "Mathematical", "Mature", "Maximum",
		"Meaningful", "Mechanical", "Medical", "Medieval", "Medium",
		"Memorable", "Mental", "Mere", "Middle", "Mild",
		"Minimal", "Minimum", "Minute", "Miserable", "Misleading",
		"Missing", "Mixed", "Mobile", "Moderate", "Modern", "Modest", "Monthly",
		"Moral", "Motor", "Moving", "Multiple", "Municipal", "Musical",
		"Mutual", "Mysterious", "Narrative", "Narrow",
		"National", "Nationwide", "Native", "Natural", "Naval", "Near",
		"Nearby", "Neat", "Necessary", "Negative", "Neighbouring", "Nervous",
		"Net", "Neutral", "New", "Next", "Nice", "Noble", "Noisy", "NonProfit",
		"Normal", "North", "Northern", "Notable", "Notorious", "Novel",
		"Nuclear", "Numerous", "Objective", "Obvious", "Occasional", "Odd",
		"Offensive", "Official", "Ok", "Old", "OldFashioned", "Ongoing",
		"Online", "Only", "Open", "Operational", "Opposed", "Opposite",
		"Optical", "Optimistic", "Orange", "Ordinary", "Organic",
		"Organizational", "Organized", "Original", "Other", "Outdoor", "Outer",
		"Outside", "Outstanding", "Overall", "Overseas", "Overwhelming", "Own",
		"Painful", "Pale", "Parallel", "Parental", "Parliamentary", "PartTime",
		"Partial", "Particular", "Passionate", "Passive", "Past", "Patient",
		"Peaceful", "Peculiar", "Perfect", "Permanent", "Persistent",
		"Personal", "Philosophical", "Physical", "Pink", "Plain", "Plastic",
		"Pleasant", "Pleased", "Plus", "Pointed", "Poisonous", "Polite",
		"Political", "Poor", "Pop", "Popular", "Positive", "Possible",
		"PostWar", "Potential", "Powerful", "Practical", "Precious", "Precise",
		"Predictable", "Preliminary", "Premier", "Prepared",
		"Present", "Presidential", "Prestigious", "Pretty", "Previous",
		"Primary", "Prime", "Principal", "Prior", "Private", "Probable",
		"Problematic", "Productive", "Professional", "Profitable", "Profound",
		"Progressive", "Prominent", "Promising", "Pronounced", "Proper",
		"Prospective", "Protective", "Proud", "Provincial", "Psychiatric",
		"Psychological", "Public", "Pure", "Purple", "Qualified", "Quick",
		"Quiet", "Radical", "Random", "Rapid", "Rare",
		"Rational", "Raw", "Ready", "Real", "Realistic", "Rear", "Reasonable",
		"Recent", "Red", "Regional", "Regular", "Regulatory", "Related",
		"Relative", "Relaxed", "Relaxing", "Relevant", "Reliable", "Relieved",
		"Religious", "Reluctant", "Remarkable", "Remote", "Renowned",
		"Repeated", "Representative", "Resident", "Residential", "Respective",
		"Responsible", "Retired", "Reverse", "Revolutionary", "Rich",
		"Ridiculous", "Right", "Risky", "Rival", "Robust", "Romantic", "Rough",
		"Round", "Routine", "Royal", "Rubber", "Rude", "Rural", "Sacred", "Sad",
		"Safe", "Same", "Satisfied", "Scary", "Scattered",
		"Sceptical", "Scientific", "Secondary", "Secret", "Secular", "Secure",
		"Selective", "Senior", "Sensible", "Sensitive", "Separate", "Serial",
		"Serious", "Severe", "Shallow", "Shaped", "Sharp",
		"Sheer", "Shiny", "Shocked", "Shocking", "Short", "ShortTerm", "Shut",
	}
}

func adjectiveOne() []string {
	return []string{
		"Shy", "Significant", "Silent", "Silly", "Silver", "Similar",
		"Simple", "Sincere", "Single", "Situated", "Ski", "Skilled", "Slight",
		"Slow", "Small", "Smart", "Smooth", "SoCalled", "Social", "Socialist",
		"Soft", "Solar", "Sole", "Solid", "Solo", "Sophisticated",
		"Sound", "South", "Spare", "Special", "Specialist",
		"Specialized", "Specific", "Spectacular", "Spicy", "Spiritual",
		"Spoken", "Sporting", "Square", "Stable", "Standard", "Standing",
		"Stark", "State", "Statistical", "Steady", "Steep", "Sticky", "Stiff",
		"Still", "Straight", "Straightforward", "Strange", "Strategic",
		"Strict", "Striking", "Strong", "Structural", "Stunning",
		"Subject", "Subsequent", "Substantial", "Subtle", "Suburban",
		"Successful", "Successive", "Sudden", "Sufficient", "Suitable", "Super",
		"Superb", "Superior", "Supportive", "Supreme", "Sure", "Surgical",
		"Surprised", "Surprising", "Surrounding", "Suspicious", "Sustainable",
		"Sweet", "Symbolic", "Sympathetic", "Systematic", "Tactical",
		"Talented", "Tall", "Technical", "Technological",
		"Temporary", "Tender", "Terminal", "Terrible", "Terrific", "Theatrical",
		"Theoretical", "Thick", "Thin", "Thirsty", "Thorough",
		"ThoughtProvoking", "Thoughtful", "Thrilled", "Tidy", "Tight",
		"Timely", "Tiny", "Tired", "Top", "Total", "Tough", "Toxic", "Toy",
		"Traditional", "Transparent", "Tremendous", "Tribal",
		"Tropical", "True", "Twin", "Typical", "Ultimate",
		"Unable", "Unacceptable", "Uncomfortable", "Underground",
		"Underlying", "Unemployed", "Unexpected", "Unfair", "Unfortunate",
		"Unique", "United", "Universal", "Unknown", "Unlikely",
		"Unnecessary", "Unpleasant", "Unprecedented", "Unusual", "Upcoming",
		"Upper", "Upset", "Upstairs", "Urban", "Urgent", "Used", "Useful",
		"Useless", "Usual", "Vague", "Valid", "Valuable", "Variable", "Varied",
		"Various", "Vast", "Verbal", "Vertical", "Very", "Viable", "Vibrant",
		"Virtual", "Visible", "Visual", "Vital", "Vocal",
		"Voluntary", "Vulnerable", "Warm", "Waste", "Weak", "Wealthy", "Weekly",
		"Weird", "Welcome", "Well", "West", "Western", "Wet", "White", "Whole",
		"Wide", "Widespread", "Wild", "Willing", "Wise", "Wonderful", "Wooden",
		"Working", "Worldwide", "Worried", "Worse", "Worst", "Worth",
		"Worthwhile", "Worthy", "Written", "Wrong", "Yellow",
	}
}
