package manifest

func nounTwo() []string {
	return []string{
		"Layers", "Layouts", "Leaders", "Leaderships", "Leads", "Leaflets",
		"Leagues", "Leaks", "Leaps", "Learnings", "Leathers",
		"Leaves", "Lectures", "Lefts", "Legacies", "Legends", "Legislations",
		"Legislatures", "Legs", "Leisures", "Lemons", "Lengths", "Lens",
		"Lessons", "Letters", "Levels", "Liberals", "Liberations", "Liberties",
		"Libraries", "Licences", "Lies", "Lifestyles", "Lifetimes", "Lifts",
		"Lightings", "Lights", "Likelihoods", "Likes", "Limbs", "Limitations",
		"Limits", "LineUps", "Lines", "Links", "Lions", "Lips", "Liquids",
		"Listeners", "Listings", "Lists", "Literacies", "Literatures", "Litres",
		"Litters", "Livers", "Lives", "Livings", "Loads", "Loans", "Lobbies",
		"Locals", "Locations", "Locks", "Logics", "Logos", "Logs", "Looks",
		"Loops", "Lords", "Lorries", "Losses", "Lotteries", "Loves", "Lows",
		"Loyalties", "Luck", "Lunches", "Lungs", "Luxuries", "Lyrics",
		"Machineries", "Machines", "Magazines", "Magics", "Magistrates",
		"Magnitudes", "Mails", "Mainlands", "Mainstreams", "Maintenances",
		"Majorities", "MakeUps", "Makes", "Makings", "Malls",
		"Managements", "Managers", "Mandates", "Manipulations", "Manners",
		"Manufacturings", "Manuscripts", "Maps", "Marathons",
		"Marches", "Margins", "Markers", "Marketings", "Marketplaces",
		"Markets", "Marks", "Marriages", "Masks", "Masses",
		"Masters", "Matches", "Materials", "Mates", "Mathematics", "Maths",
		"Matters", "Maximums", "Mayors", "Mays", "Meals", "Meanings", "Means",
		"Meantimes", "Measurements", "Measures", "Meats", "Mechanics",
		"Mechanisms", "Medals", "Media", "Medications", "Medicines",
		"Meditations", "Meetings", "Melodies", "Members", "Memberships",
		"Memoirs", "Memorials", "Memories", "Memos", "Mentions",
		"Mentors", "Menus", "Merchants", "Mercies", "Mergers", "Merits",
		"Messages", "Messes", "Metals", "Metaphors", "Methodologies", "Methods",
		"Metres", "Mice", "Middles", "Midnights", "Midsts", "Migrations",
		"Miles", "Milks", "Mills",
		"Minds", "Minerals", "Miners", "Mines", "Minimums", "Minings",
		"Ministers", "Ministries", "Minutes", "Miracles",
		"Mirrors", "Miseries", "Missiles", "Missions", "Mistakes", "Mixes",
		"Mixtures", "Mobiles", "Mobilities", "Mobs", "Modes",
		"Modifications", "Momenta", "Moments", "Mondays", "Moneys", "Monitors",
		"Monkeys", "Monks", "Monopolies", "Monsters", "Months", "Monuments",
		"Moods", "Moons", "Moralities", "Morals", "Mornings", "Mortgages",
		"Mothers", "Motions", "Motivations", "Motives",
		"Motorcycles", "Motorists", "Motors", "Mountains", "Mouths",
		"Movements", "Moves", "Movies", "Muds", "Mums", "Muscles",
		"Museums", "Music", "Musicals", "Musicians", "Mysteries", "Myths",
		"Nails", "Names", "Narratives", "Nationals", "Nations",
		"Natures", "Navigations", "Necessities", "Necks", "Needles", "Needs",
		"Negatives", "Neglects", "Negotiations", "Neighbourhoods", "Neighbours",
		"Nerves", "Nests", "Nets", "Networks", "News", "Newsletters",
		"Newspapers", "Niches", "Nightmares", "Nights", "Noises", "Nominations",
		"Nominees", "Nonsenses", "Noons", "Normals", "Norms", "Norths", "Noses",
		"Notebooks", "Notes", "Notices", "Notions", "Novelists", "Novels",
		"Novembers", "Numbers", "Nurseries", "Nurses", "Nursings", "Nutritions",
		"Nuts", "Obesities", "Objections", "Objectives", "Objects",
		"Obligations", "Observations", "Observers", "Obsessions", "Obstacles",
		"Occasions", "Occupations", "Occurrences", "Oceans", "Octobers", "Odds",
		"Offences", "Offerings", "Offers", "Officers", "Offices",
		"Officials", "Offspring", "Oils", "Onions", "Openings", "Operas",
		"Operations", "Operators", "Opinions", "Opponents", "Opportunities",
		"Opposites", "Oppositions", "Optimisms", "Options", "Oranges",
		"Orchestras", "Orders", "Organizations", "Organizers", "Organs",
		"Orientations", "Originals", "Origins", "Outbreaks", "Outcomes",
		"Outfits", "Outings", "Outlets", "Outlines", "Outlooks", "Outputs",
		"Outrages", "Outsiders", "Outsides", "Ovens", "Owners", "Ownerships",
		"Oxygens", "Paces", "Packages", "Packets", "Packs", "Pads", "Pages",
		"Pains", "Painters", "Paintings", "Paints", "Pairs", "Palaces", "Palms",
		"Panels", "Panics", "Pans", "Pants", "Papers", "Parades", "Paragraphs",
		"Parallels", "Parameters", "Parents", "Parishes", "Parkings", "Parks",
		"Parliaments", "Participants", "Participations", "Parties", "Partners",
		"Partnerships", "Parts", "Passages", "Passengers", "Passes", "Passings",
		"Passions", "Passports", "Passwords", "Pastors", "Pasts", "Patches",
		"Patents", "Paths", "Pathways", "Patiences", "Patients", "Patrols",
		"Patrons", "Patterns", "Pauses", "Payments", "Pays", "Peaces", "Peaks",
		"Peasants", "Peers", "Penalties", "Pencils", "Pennies", "Pens",
		"Pensions", "People", "Peoples", "Peppers", "Percentages",
		"Perceptions", "Performances", "Periods", "Permissions", "Permits",
		"Personalities", "Personnels", "Perspectives", "Petitions", "Petrols",
		"Pets", "Phases", "Phenomena", "Philosophers", "Philosophies", "Phones",
		"Photographers", "Photographies", "Photographs", "Photos", "Phrases",
		"Physicians", "Physics", "Pianos", "Picks", "Pictures", "Pieces",
		"Pigs", "Piles", "Pills", "Pilots", "Pinks", "Pins", "Pioneers",
		"Pipelines", "Pipes", "Pirates", "Pitches", "Pities", "Pits",
	}
}

func noundThree() []string {
	return []string{
		"Traces", "Tracks", "Trademarks", "Trades", "Tradings", "Traditions",
		"Traffics", "Tragedies", "Trailers", "Trails", "Trainers", "Trainings",
		"Trains", "Traits", "Transactions", "Transcripts", "Transfers",
		"Transformations", "Transitions", "Transits", "Translations",
		"Transmissions", "Transparencies", "Transportations", "Transports",
		"Traps", "Traumas", "Travellers", "Travels", "Treasures", "Treaties",
		"Treatments", "Trees", "Trends", "Trials", "Tribes", "Tribunals",
		"Tributes", "Tricks", "Tries", "Triggers", "Trios", "Trips", "Triumphs",
		"Troops", "Trophies", "Troubles", "Trousers", "Trucks", "Trustees",
		"Trusts", "Truths", "Tsunamis", "Tubes", "Tuesdays", "Tuitions",
		"Tunes", "Tunnels", "Turnouts", "Turnovers", "Turns", "Tvs",
		"Twists", "Types", "Tyres", "Umbrellas", "Uncertainties", "Uncles",
		"Undergraduates", "Understandings", "Underwears", "Unemployments",
		"Uniforms", "Unions", "Unities", "Units", "Universes", "Universities",
		"Updates", "Upgrades", "Usages", "Users", "Uses", "Utilities",
		"Vacations", "Vacuums", "Validities", "Valleys", "Values", "Vans",
		"Variables", "Variations", "Varieties", "Vegetables", "Vehicles",
		"Veins", "Ventures", "Venues", "Verdicts", "Verses", "Versions",
		"Vessels", "Veterans", "Vices", "Victories", "Videos",
		"Viewers", "Viewpoints", "Views", "Villagers", "Villages", "Violations",
		"Violences", "Virtues", "Viruses", "Visas", "Visions", "Visitors",
		"Visits", "Vitamins", "Voices", "Volumes", "Volunteers", "Votes",
		"Votings", "Vulnerabilities", "Wages", "Waiters", "Waits", "Walks",
		"Walls", "Wards", "Warehouses", "Warfares", "Warmings", "Warnings",
		"Warrants", "Warriors", "Washes", "Washings", "Wastes",
		"Watches", "Waters", "Waves", "Ways", "Weaknesses", "Wealths",
		"Weathers", "Webs", "Websites", "Weddings", "Wednesdays",
		"Weeds", "Weekends", "Weeks", "Weights", "Welcomes", "Welfares",
		"WellBeings", "Wells", "Wests", "Wheat", "Wheels", "Whispers",
		"Wholes", "Widows", "Widths", "Wildlives", "Willingnesses",
		"Wills", "Windows", "Winds", "Wines", "Wings", "Winners", "Wins",
		"Winters", "Wires", "Wisdoms", "Wishes", "Withdrawals", "Witnesses",
		"Wits", "Wonders", "Woods", "Wools", "Words", "Workers", "Workforces",
		"Workouts", "Workplaces", "Works", "Workshops", "Worlds", "Worms",
		"Worries", "Worses", "Worships", "Worsts", "Worths", "Wounds", "Wrists",
		"Writers", "Writings", "Wrongs", "Yards", "Years", "Yellows",
		"Yesterdays", "Yields", "Zones",
		"Implementations", "Implications", "Importances", "Imports",
		"Impressions", "Imprisonments", "Improvements", "Inabilities",
		"Incentives", "Inches", "Incidences", "Incidents", "Inclusions",
		"Incomes", "Increases", "Independences", "Indications", "Indicators",
		"Indices", "Indictments", "Individuals", "Industries", "Inequalities",
		"Infections", "Inflations", "Influences", "Information",
		"Infos", "Infrastructures", "Ingredients", "Inhabitants", "Initiatives",
		"Injections", "Injuries", "Injustices", "Inks",
		"Innovations", "Inputs", "Inquiries", "Insects", "Insertions",
		"Insiders", "Insides", "Insights", "Inspections", "Inspectors",
		"Inspirations", "Installations", "Instances", "Instincts", "Institutes",
		"Institutions", "Instructions", "Instructors", "Instruments", "Insults",
		"Insurances", "Intakes", "Integrations", "Integrities", "Intellectuals",
		"Intelligences", "Intensities", "Intentions", "Intents", "Interactions",
		"Interests", "Interfaces", "Interferences", "Interiors",
		"Interpretations", "Intervals", "Interventions", "Interviews",
		"Introductions", "Invasions", "Inventions", "Investigations",
		"Investigators", "Investments", "Investors", "Invitations",
		"Involvements", "Ironies", "Irons", "Islands", "Isolations", "Issues",
		"Items", "Its", "Jackets", "Jails", "Jams", "Januaries", "Jazzes",
		"Jeans", "Jets", "Jewelleries", "Jobs", "Joints", "Jokes",
		"Journalisms", "Journalists", "Journals", "Journeys", "Joys",
		"Judgements", "Judges", "Juices", "Julies", "Jumps", "Junctions",
		"Junes", "Juries", "Jurisdictions", "Justices", "Justifications",
		"Keyboards", "Keys", "Kicks", "Kidneys", "Kilometres",
		"Kinds", "Kingdoms", "Kings", "Kisses", "Kitchens", "Kits", "Knees",
		"Knives", "Knocks", "Knowledges", "Labels", "Laboratories", "Labours",
		"Labs", "Lacks", "Ladders", "Lakes", "Lamps",
		"Landings", "Landlords", "Landmarks", "Lands", "Landscapes", "Lanes",
		"Languages", "Laps", "Laptops", "Lasers", "Lasts", "Latests", "Laughs",
		"Laughters", "Launches", "Lawns", "Laws", "Lawsuits", "Lawyers",
	}
}

func nounOne() []string {
	return []string{
		"Rivals", "Rivers", "Roads", "Robberies", "Robots", "Rockets", "Rocks",
		"Rods", "Roles", "Rolls", "Romances", "Roofs", "Rooms", "Roots",
		"Ropes", "Roses", "Rotations", "Rounds", "Routes", "Routines", "Rows",
		"Rubbers", "Rubbishes", "Rugbies", "Ruins", "Rules", "Rulings",
		"Rumours", "Runners", "Runnings", "Runs", "Rushes", "Sacrifices",
		"Safeties", "Sailings", "Sailors", "Sails", "Saints", "Sakes", "Salads",
		"Salaries", "Sales", "Salts", "Samples", "Sanctions", "Sands",
		"Sandwiches", "Satellites", "Satisfactions", "Saturdays", "Sauces",
		"Savings", "Says", "Scales", "Scandals", "Scares", "Scenarios",
		"Scenes", "Schedules", "Schemes", "Scholars", "Scholarships", "Schools",
		"Sciences", "Scientists", "Scopes", "Scores", "Scratches", "Screams",
		"Screenings", "Screens", "Screws", "Scripts", "Scrutinies",
		"Sculptures", "Seals", "Searches", "Seas", "Seasons", "Seats",
		"Seconds", "Secretaries", "Secrets", "Sections", "Sectors",
		"Securities", "Seeds", "Seekers", "Segments", "Selections", "Selves",
		"Seminars", "Senators", "Sensations", "Senses", "Sensitivities",
		"Sentences", "Sentiments", "Separations", "Septembers", "Sequences",
		"Series", "Servants", "Services", "Sessions", "SetUps", "Sets",
		"Settings", "Settlements", "Settlers", "Shades",
		"Shadows", "Shakes", "Shames", "Shapes", "Shareholders", "Shares",
		"Sheep", "Sheets", "Shells", "Shelters", "Shelves", "Shifts",
		"Shippings", "Ships", "Shirts", "Shocks", "Shoes", "Shootings",
		"Shoots", "Shoppings", "Shops", "Shores", "Shortages", "Shots",
		"Shoulders", "Shouts", "Showers", "Shows", "Siblings", "Sides", "Sighs",
		"Sights", "Signals", "Signatures", "Significances", "Signs", "Silences",
		"Silks", "Silver", "Similarities", "Simulations", "Singers", "Singings",
		"Singles", "Sins", "Sirs", "Sites", "Situations", "Sizes",
		"Sketches", "Skies", "Skiings", "Skills", "Skins", "Skirts", "Skis",
		"Skulls", "Sleeps", "Slices", "Slides",
		"Slogans", "Slopes", "Slots", "Smartphones", "Smells", "Smiles",
		"Smokes", "Smokings", "Snakes", "Snows", "Soaps", "Soccers",
		"Societies", "Socks", "Softwares", "Soils", "Soldiers", "Solicitors",
		"Solidarities", "Solids", "Solos", "Solutions", "Songs", "Sons",
		"Sorts", "Souls", "Sounds", "Soups", "Sources",
		"Sovereignties", "Spaces", "Spams", "Spans", "Speakers", "Specialists",
		"Species", "Specifications", "Specimens", "Spectacles", "Spectators",
		"Spectra", "Speculations", "Speeches", "Speeds", "Spellings", "Spells",
		"Spendings", "Spheres", "Spices", "Spiders", "Spies", "Spines", "Spins",
		"Spirits", "Spites", "Splits", "Spokesmen", "Spokespeople", "Sponsors",
		"Sponsorships", "Spoons", "Sports", "Spotlights", "Spots", "Spouses",
		"Spreads", "Springs", "Squads", "Squares", "Stabilities", "Stadiums",
		"Staffs", "Stages", "Stairs", "Stakes", "Stalls", "Stamps", "Stances",
		"Standards", "Stands", "Stars", "Starts", "Statements", "States",
		"Stations", "Statistics", "Statues", "Status", "Stays", "Steams",
		"Steels", "Stems", "Steps", "Stereotypes", "Sticks", "Stimuli",
		"Stocks", "Stomachs", "Stones", "Stops", "Storages", "Stores",
		"Stories", "Storms", "Strains", "Strands", "Strangers", "Strategies",
		"Streams", "Streets", "Strengths", "Stresses", "Stretches", "Strikes",
		"Strings", "Strips", "Strokes", "Structures", "Struggles", "Students",
		"Studies", "Studios", "Stuffs", "Styles", "Subjects", "Submissions",
		"Subscribers", "Subscriptions", "Subsidies", "Substances",
		"Substitutes", "Substitutions", "Suburbs", "Successes", "Successions",
		"Successors", "Sufferings", "Sugars", "Suggestions",
		"Suites", "Suits", "Summaries", "Summers", "Summits", "Sums", "Sundays",
		"Suns", "Supermarkets", "Supervisions", "Supervisors", "Supplements",
		"Supplies", "Supporters", "Supports", "Surfaces", "Surgeons",
		"Surgeries", "Surges", "Surplus", "Surprises", "Surveillances",
		"Surveys", "Survivals", "Survivors", "Suspects", "Suspensions",
		"Suspicions", "Sweaters", "Sweets", "Swimmings", "Swims", "Swings",
		"Switches", "Swords", "Symbols", "Sympathies", "Symptoms", "Syndromes",
		"Syntheses", "Systems", "TShirts", "Tables", "Tablets", "Tackles",
		"Tactics", "Tags", "Tails", "Talents", "Tales", "Talks", "Tanks",
		"Tapes", "Taps", "Targets", "Tasks", "Tastes", "Taxes", "Taxis",
		"Taxpayers", "Teachers", "Teachings", "Teams", "Tears", "Teas",
		"Techniques", "Technologies", "Teenagers", "Teens", "Teeth",
		"Telephones", "Televisions", "Temperatures", "Temples", "Tenants",
		"Tendencies", "Tennis", "Tensions", "Tents", "Tenures", "Terminals",
		"Terms", "Terrains", "Territories",
		"Testimonies", "Testings", "Tests", "Textbooks", "Texts",
		"Textures", "Thanks", "Theatres", "Thefts", "Themes", "Theologies",
		"Theories", "Therapies", "Therapists", "Theses", "Thieves", "Things",
		"Thinkings", "Thirds", "Thoughts", "Threads", "Threats", "Thresholds",
		"Throats", "Thumbs", "Thursdays", "Tickets", "Tides", "Ties", "Timbers",
		"Times", "Timings", "Tins", "Tips", "Tissues", "Titles", "Tobaccos",
		"Todays", "Toes", "Toilets", "Tolerances", "Tolls", "Tomatoes",
		"Tomorrows", "Tones", "Tongues", "Tonights", "Tonnes", "Tons", "Tools",
		"Topics", "Tops", "Tortoises", "Totals", "Touches", "Tourisms",
		"Tourists", "Tournaments", "Tours", "Towels", "Towers", "Towns", "Toys",
	}
}
