package manifest

func PluralNoun() []string {
	noun := make([]string, 0)
	for _, fn := range []strSliceFnT{nounFour, noundThree, nounTwo, nounOne, nounFive, nounSix, nounSeven} {
		noun = append(noun, fn()...)
	}

	return noun
}

func nounSeven() []string {
	return []string{
		"Registers", "Registrations", "Regrets", "Regulations", "Regulators",
		"Rehabilitations", "Reigns", "Rejections", "Relations", "Relationships",
		"Relatives", "Releases", "Relevances", "Reliabilities", "Reliefs",
		"Religions", "Remainders", "Remains", "Remarks", "Remedies",
		"Reminders", "Removals", "Rentals", "Rents", "Repairs", "Repeats",
		"Replacements", "Replies", "Reporters", "Reportings", "Reports",
		"Representations", "Representatives", "Reproductions", "Republics",
		"Reputations", "Requests", "Requirements", "Rescues", "Researchers",
		"Researches", "Reservations", "Reserves", "Residences", "Residents",
		"Residues", "Resignations", "Resistances", "Resolutions", "Resorts",
		"Resources", "Respects", "Responses", "Responsibilities", "Restaurants",
		"Restorations", "Restraints", "Restrictions", "Rests", "Results",
		"Retails", "Retirements", "Retreats", "Returns", "Revelations",
		"Revenges", "Revenues", "Reverses", "Reviews", "Revisions", "Revivals",
		"Revolutions", "Rewards", "Rhetorics", "Rhythms", "Rices", "Rides",
		"Rifles", "Rights", "Rings", "Riots", "Rises", "Risks", "Rituals",
		"Documentations", "Documents", "Dogs", "Dollars", "Domains",
		"Dominances", "Donations", "Donors", "Doors", "Doses", "Dots", "Doubts",
		"Downloads", "Downtowns", "Dozens", "Drafts", "Dramas", "Drawings",
		"Dreams", "Dresses", "Drinks", "Drivers", "Drives", "Drivings", "Drops",
		"Droughts", "Drums", "Duos", "Durations", "Dusts", "Duties",
		"Dvds", "Dynamics", "Earnings", "Ears", "Earthquakes", "Earths",
		"Eases", "Easts", "Echoes", "Economics", "Economies", "Economists",
		"Edges", "Editions", "Editors", "Educations", "Educators",
		"Effectivenesses", "Effects", "Efficiencies", "Efforts", "Eggs", "Egos",
		"Elbows", "Elections", "Electricities", "Electronics", "Elements",
		"Elephants", "Elites", "Emails", "Embarrassments", "Embassies",
		"Emergences", "Emergencies", "Emissions", "Emotions", "Emphases",
		"Empires", "Employees", "Employers", "Employments", "Encounters",
		"Encouragements", "Endeavours", "Endings", "Endorsements", "Ends",
		"Enemies", "Energies", "Enforcements", "Engagements", "Engineerings",
		"Engineers", "Engines", "Enquiries", "Enterprises", "Entertainments",
		"Enthusiasms", "Enthusiasts", "Entities", "Entrances", "Entrepreneurs",
		"Entries", "Envelopes", "Environments", "Epidemics", "Episodes",
		"Equalities", "Equals", "Equations", "Equipment", "Equivalents", "Eras",
		"Errors", "Escapes", "Essays", "Essences", "Establishments", "Estates",
		"Estimates", "Ethics", "Euros", "Evaluations", "Evenings", "Events",
		"Evidence", "Evils", "Evolutions", "Examinations", "Examples", "Exams",
		"Excellences", "Exceptions", "Excesses", "Exchanges", "Excitements",
		"Exclusions", "Excuses", "Executives", "Exercises",
		"Exhibitions", "Exhibits", "Exiles", "Existences", "Exits",
		"Expansions", "Expectations", "Expeditions", "Expenditures", "Expenses",
		"Experiences", "Experiments", "Expertises", "Experts", "Explanations",
		"Exploitations", "Explorations", "Explosions", "Explosives", "Exports",
		"Exposures", "Expressions", "Extensions", "Extents", "Extracts",
		"Extras", "Extremes", "Eyes", "Fabrics", "Faces",
		"Facilities", "Factions", "Factories", "Factors", "Facts", "Faculties",
		"Failures", "Fairnesses", "Faiths", "Falls", "Fames", "Families",
		"Fans", "Fantasies", "Fares", "Farmers", "Farmings", "Farms",
		"Fashions", "Fates", "Fats", "Faults", "Favourites", "Favours", "Fears",
		"Feathers", "Feats", "Features", "Februaries", "Feedbacks", "Feeds",
		"Feelings", "Feels", "Fees", "Feet", "Feminists", "Fences",
		"Festivals", "Fevers", "Fibres", "Fictions", "Fields", "Fighting",
		"Fights", "Figures", "Files", "FilmMakers", "Films", "Filters",
		"Finals", "Finances", "Findings", "Fines", "Fingers", "Finishes",
		"Firefighters", "Fires", "Fireworks", "Firms", "Firsts",
		"Fish", "Fishings", "Fitnesses", "Fits", "Fixes", "Fixtures", "Flags",
		"Flames", "Flashes", "Flats", "Flavours", "Flaws", "Fleets", "Fleshes",
		"Flexibilities", "Flies", "Flights", "Floods", "Floors", "Flours",
		"Flowers", "Flows", "Fluids", "Flus", "Flyings", "Foci", "Folds",
		"Folks", "Followings", "Foods", "Fools", "Footages", "Footballs",
		"Forces", "Forecasts", "Foreigners", "Forests", "Forks", "Formations",
		"Formats", "Forms", "Formulae", "Fortunes", "Forums", "Fossils",
		"Foundations", "Founders", "Fractions", "Fragments", "Frames",
		"Frameworks", "Franchises", "Frauds", "Freedoms", "Frequencies",
		"Fridays", "Fridges", "Friends", "Friendships", "Frogs", "Fronts",
		"Fruits", "Frustrations", "Fuels", "Functions", "Fundings",
		"Fundraisings", "Funds", "Funerals", "Funs", "Furnitures", "Furs",
		"Futures", "Gains", "Galleries", "Gallons", "Gamblings", "Games",
		"Gamings", "Gaps", "Garages", "Gardens", "Gases", "Gates",
		"Gatherings", "Gazes", "Gears", "Genders", "Generations", "Genes",
		"Genius", "Genres", "Gentlemen", "Geographies", "Gestures",
		"Ghosts", "Giants", "Gifts", "Gigs", "Glances", "Glasses", "Glimpses",
		"Globalizations", "Globes", "Glories", "Gloves", "Goals", "Gods",
		"Goes", "Gold", "Golfs", "Goodbyes", "Goodnesses", "Goods",
		"Governances", "Governments", "Governors", "Graces", "Grades",
		"Graduates", "Grains", "Grandfathers", "Grandmothers", "Grandparents",
		"Grants", "Graphics", "Grasps", "Grasses", "Graves", "Gravities",
	}
}

func nounFive() []string {
	return []string{
		"Placements", "Places", "Planes", "Planets", "Plannings", "Plans",
		"Plants", "Plastics", "Plates", "Platforms", "Players", "Plays",
		"Pleas", "Pleasures", "Pledges", "Plots", "Plugs", "Plus", "Pockets",
		"Poems", "Poetries", "Poets", "Points", "Poisons", "Poles", "Police",
		"Policemen", "Policies", "Politicians", "Politics", "Polls",
		"Pollutions", "Ponds", "Pools", "Pops", "Popularities", "Populations",
		"Portfolios", "Portions", "Portraits", "Ports", "Positions",
		"Positives", "Possessions", "Possibilities", "Posters", "Posts",
		"Potatoes", "Potentials", "Pots", "Pounds", "Poverties", "Powders",
		"Powers", "Practices", "Practitioners", "Praises", "Prayers",
		"Precedents", "Precisions", "Predators", "Predecessors", "Predictions",
		"Preferences", "Pregnancies", "Prejudices", "Premises", "Premiums",
		"Preparations", "Prescriptions", "Presences", "Presentations",
		"Presents", "Preservations", "Presidencies", "Presidents", "Presses",
		"Pressures", "Prevalences", "Preventions", "Preys", "Prices", "Prides",
		"Priests", "Princes", "Princesses", "Principals", "Principles",
		"Printers", "Printings", "Prints", "Priorities", "Prisons",
		"Privacies", "Privatizations", "Privileges", "Prizes", "Probabilities",
		"Probes", "Problems", "Procedures", "Proceedings", "Proceeds",
		"Processes", "Processings", "Processors", "Producers", "Produces",
		"Productions", "Productivities", "Products", "Professionals",
		"Professions", "Professors", "Profiles", "Profits", "Programmes",
		"Programmings", "Programs", "Progresses", "Projections", "Projects",
		"Promises", "Promotions", "Proofs", "Propagandas", "Properties",
		"Proportions", "Proposals", "Propositions", "Prosecutions",
		"Prosecutors", "Prospects", "Prosperities", "Protections", "Proteins",
		"Protesters", "Protests", "Protocols", "Provinces", "Provisions",
		"Psychologies", "Psychologists", "Publications", "Publicities",
		"Publics", "Publishings", "Pubs", "Pulls", "Pulses", "Pumps", "Punches",
		"Punishments", "Punks", "Pupils", "Purchases", "Purples", "Purposes",
		"Pursuits", "Pushes", "Puzzles", "Qualifications", "Qualities",
		"Quantities", "Quarters", "Queens", "Queries", "Questionnaires",
		"Questions", "Quests", "Queues", "Quotas", "Quotations", "Quotes",
		"Races", "Racings", "Radars", "Radiations",
		"Radios", "Rages", "Raids", "Rails", "Railways", "Rains", "Rallies",
		"Ranges", "Rankings", "Ranks", "Rates", "Ratings", "Ratios",
		"Rats", "Rays", "Reaches", "Reactions", "Readers", "Readings",
		"Cuts", "Cuttings", "Cycles", "Dads", "Dairies", "Damages", "Dams",
		"Dancers", "Dances", "Dancings", "Dangers", "Darknesses", "Darks",
		"Databases", "Dates", "Daughters", "Dawns", "Days",
		"Deadlines", "Dealers", "Deals", "Debates", "Debris", "Debts",
		"Debuts", "Decades", "Decembers", "DecisionMakings", "Decisions",
		"Decks", "Declarations", "Declines", "Decorations", "Decreases",
		"Dedications", "Deeds", "Defaults", "Defeats", "Defects", "Defences",
		"Defenders", "Deficiencies", "Deficits", "Definitions", "Degrees",
		"Delays", "Delegates", "Delegations", "Delights", "Deliveries",
		"Demands", "Democracies", "Demons", "Demonstrations", "Denials",
		"Densities", "Dentists", "Departments", "Departures", "Dependences",
		"Deployments", "Deposits", "Depressions", "Depths", "Deputies",
		"Descents", "Descriptions", "Deserts", "Designers", "Designs",
		"Desires", "Desks", "Desktops", "Destinations", "Destructions",
		"Details", "Detections", "Detectives", "Detentions", "Determinations",
		"Developments", "Devices", "Devils", "Diagnoses", "Diagrams",
		"Dialogues", "Diamonds", "Diaries", "Dictators", "Dictionaries",
		"Diets", "Differences", "Difficulties", "Dignities", "Dilemmas",
		"Dimensions", "Dinners", "Diplomats", "Directions", "Directories",
		"Directors", "Dirts", "Disabilities", "Disadvantages", "Disagreements",
		"Disappointments", "Disciplines", "Disclosures",
		"Discounts", "Discourses", "Discoveries", "Discretions",
		"Discs", "Discussions", "Dishes",
		"Disks", "Dislikes", "Dismissals", "Disorders", "Displays", "Disposals",
		"Disputes", "Disruptions", "Distances", "Distinctions", "Distresses",
		"Distributions", "Districts", "Diversities", "Dives", "Divides",
		"Divisions", "Divorces", "Doctors", "Doctrines", "Documentaries",
		"Hungers", "Huntings", "Hunts", "Hurricanes", "Hurries", "Hurts",
		"Hydrogens", "Hypotheses", "Ices", "Icons", "Ideals", "Ideas",
		"Identifications", "Identities", "Ideologies", "Ids",
		"Ignorances", "Illusions", "Illustrations", "Imageries",
		"Images", "Imaginations", "Immigrations", "Impacts",
		"Realities", "Realizations", "Realms", "Rears", "Reasonings", "Reasons",
		"Rebellions", "Rebels", "Receipts", "Receivers", "Receptions",
		"Recessions", "Recipes", "Recipients", "Recognitions",
		"Recommendations", "Reconstructions", "Recordings", "Records",
		"Recoveries", "Recruitments", "Recruits", "Reductions",
		"Referees", "References", "Referendums", "Reflections", "Reforms",
		"Refusals", "Regards", "Regimes", "Regions",
	}
}

func nounTwo() []string {
	return []string{
		"Layers", "Layouts", "Leaders", "Leaderships", "Leads", "Leaflets",
		"Leagues", "Leaks", "Leaps", "Learnings", "Leathers",
		"Leaves", "Lectures", "Lefts", "Legacies", "Legends", "Legislations",
		"Legislatures", "Legs", "Leisures", "Lemons", "Lengths", "Lens",
		"Lessons", "Letters", "Levels", "Liberals", "Liberations", "Liberties",
		"Libraries", "Licences", "Lies", "Lifestyles", "Lifetimes", "Lifts",
		"Lightings", "Lights", "Likelihoods", "Likes", "Limbs", "Limitations",
		"Limits", "LineUps", "Lines", "Links", "Lions", "Lips", "Liquids",
		"Listeners", "Listings", "Lists", "Literacies", "Literatures", "Litres",
		"Litters", "Livers", "Lives", "Livings", "Loads", "Loans", "Lobbies",
		"Locals", "Locations", "Locks", "Logics", "Logos", "Logs", "Looks",
		"Loops", "Lords", "Lorries", "Losses", "Lotteries", "Loves", "Lows",
		"Loyalties", "Luck", "Lunches", "Lungs", "Luxuries", "Lyrics",
		"Machineries", "Machines", "Magazines", "Magics", "Magistrates",
		"Magnitudes", "Mails", "Mainlands", "Mainstreams", "Maintenances",
		"Majorities", "MakeUps", "Makes", "Makings", "Malls",
		"Managements", "Managers", "Mandates", "Manipulations", "Manners",
		"Manufacturings", "Manuscripts", "Maps", "Marathons",
		"Marches", "Margins", "Markers", "Marketings", "Marketplaces",
		"Markets", "Marks", "Marriages", "Masks", "Masses",
		"Masters", "Matches", "Materials", "Mates", "Mathematics", "Maths",
		"Matters", "Maximums", "Mayors", "Mays", "Meals", "Meanings", "Means",
		"Meantimes", "Measurements", "Measures", "Meats", "Mechanics",
		"Mechanisms", "Medals", "Media", "Medications", "Medicines",
		"Meditations", "Meetings", "Melodies", "Members", "Memberships",
		"Memoirs", "Memorials", "Memories", "Memos", "Mentions",
		"Mentors", "Menus", "Merchants", "Mercies", "Mergers", "Merits",
		"Messages", "Messes", "Metals", "Metaphors", "Methodologies", "Methods",
		"Metres", "Mice", "Middles", "Midnights", "Midsts", "Migrations",
		"Miles", "Milks", "Mills",
		"Minds", "Minerals", "Miners", "Mines", "Minimums", "Minings",
		"Ministers", "Ministries", "Minutes", "Miracles",
		"Mirrors", "Miseries", "Missiles", "Missions", "Mistakes", "Mixes",
		"Mixtures", "Mobiles", "Mobilities", "Mobs", "Modes",
		"Modifications", "Momenta", "Moments", "Mondays", "Moneys", "Monitors",
		"Monkeys", "Monks", "Monopolies", "Monsters", "Months", "Monuments",
		"Moods", "Moons", "Moralities", "Morals", "Mornings", "Mortgages",
		"Mothers", "Motions", "Motivations", "Motives",
		"Motorcycles", "Motorists", "Motors", "Mountains", "Mouths",
		"Movements", "Moves", "Movies", "Muds", "Mums", "Muscles",
		"Museums", "Music", "Musicals", "Musicians", "Mysteries", "Myths",
		"Nails", "Names", "Narratives", "Nationals", "Nations",
		"Natures", "Navigations", "Necessities", "Necks", "Needles", "Needs",
		"Negatives", "Neglects", "Negotiations", "Neighbourhoods", "Neighbours",
		"Nerves", "Nests", "Nets", "Networks", "News", "Newsletters",
		"Newspapers", "Niches", "Nightmares", "Nights", "Noises", "Nominations",
		"Nominees", "Nonsenses", "Noons", "Normals", "Norms", "Norths", "Noses",
		"Notebooks", "Notes", "Notices", "Notions", "Novelists", "Novels",
		"Novembers", "Numbers", "Nurseries", "Nurses", "Nursings", "Nutritions",
		"Nuts", "Obesities", "Objections", "Objectives", "Objects",
		"Obligations", "Observations", "Observers", "Obsessions", "Obstacles",
		"Occasions", "Occupations", "Occurrences", "Oceans", "Octobers", "Odds",
		"Offences", "Offerings", "Offers", "Officers", "Offices",
		"Officials", "Offspring", "Oils", "Onions", "Openings", "Operas",
		"Operations", "Operators", "Opinions", "Opponents", "Opportunities",
		"Opposites", "Oppositions", "Optimisms", "Options", "Oranges",
		"Orchestras", "Orders", "Organizations", "Organizers", "Organs",
		"Orientations", "Originals", "Origins", "Outbreaks", "Outcomes",
		"Outfits", "Outings", "Outlets", "Outlines", "Outlooks", "Outputs",
		"Outrages", "Outsiders", "Outsides", "Ovens", "Owners", "Ownerships",
		"Oxygens", "Paces", "Packages", "Packets", "Packs", "Pads", "Pages",
		"Pains", "Painters", "Paintings", "Paints", "Pairs", "Palaces", "Palms",
		"Panels", "Panics", "Pans", "Pants", "Papers", "Parades", "Paragraphs",
		"Parallels", "Parameters", "Parents", "Parishes", "Parkings", "Parks",
		"Parliaments", "Participants", "Participations", "Parties", "Partners",
		"Partnerships", "Parts", "Passages", "Passengers", "Passes", "Passings",
		"Passions", "Passports", "Passwords", "Pastors", "Pasts", "Patches",
		"Patents", "Paths", "Pathways", "Patiences", "Patients", "Patrols",
		"Patrons", "Patterns", "Pauses", "Payments", "Pays", "Peaces", "Peaks",
		"Peasants", "Peers", "Penalties", "Pencils", "Pennies", "Pens",
		"Pensions", "People", "Peoples", "Peppers", "Percentages",
		"Perceptions", "Performances", "Periods", "Permissions", "Permits",
		"Personalities", "Personnels", "Perspectives", "Petitions", "Petrols",
		"Pets", "Phases", "Phenomena", "Philosophers", "Philosophies", "Phones",
		"Photographers", "Photographies", "Photographs", "Photos", "Phrases",
		"Physicians", "Physics", "Pianos", "Picks", "Pictures", "Pieces",
		"Pigs", "Piles", "Pills", "Pilots", "Pinks", "Pins", "Pioneers",
		"Pipelines", "Pipes", "Pirates", "Pitches", "Pities", "Pits",
	}
}

func noundThree() []string {
	return []string{
		"Traces", "Tracks", "Trademarks", "Trades", "Tradings", "Traditions",
		"Traffics", "Tragedies", "Trailers", "Trails", "Trainers", "Trainings",
		"Trains", "Traits", "Transactions", "Transcripts", "Transfers",
		"Transformations", "Transitions", "Transits", "Translations",
		"Transmissions", "Transparencies", "Transportations", "Transports",
		"Traps", "Traumas", "Travellers", "Travels", "Treasures", "Treaties",
		"Treatments", "Trees", "Trends", "Trials", "Tribes", "Tribunals",
		"Tributes", "Tricks", "Tries", "Triggers", "Trios", "Trips", "Triumphs",
		"Troops", "Trophies", "Troubles", "Trousers", "Trucks", "Trustees",
		"Trusts", "Truths", "Tsunamis", "Tubes", "Tuesdays", "Tuitions",
		"Tunes", "Tunnels", "Turnouts", "Turnovers", "Turns", "Tvs",
		"Twists", "Types", "Tyres", "Umbrellas", "Uncertainties", "Uncles",
		"Undergraduates", "Understandings", "Underwears", "Unemployments",
		"Uniforms", "Unions", "Unities", "Units", "Universes", "Universities",
		"Updates", "Upgrades", "Usages", "Users", "Uses", "Utilities",
		"Vacations", "Vacuums", "Validities", "Valleys", "Values", "Vans",
		"Variables", "Variations", "Varieties", "Vegetables", "Vehicles",
		"Veins", "Ventures", "Venues", "Verdicts", "Verses", "Versions",
		"Vessels", "Veterans", "Vices", "Victories", "Videos",
		"Viewers", "Viewpoints", "Views", "Villagers", "Villages", "Violations",
		"Violences", "Virtues", "Viruses", "Visas", "Visions", "Visitors",
		"Visits", "Vitamins", "Voices", "Volumes", "Volunteers", "Votes",
		"Votings", "Vulnerabilities", "Wages", "Waiters", "Waits", "Walks",
		"Walls", "Wards", "Warehouses", "Warfares", "Warmings", "Warnings",
		"Warrants", "Warriors", "Washes", "Washings", "Wastes",
		"Watches", "Waters", "Waves", "Ways", "Weaknesses", "Wealths",
		"Weathers", "Webs", "Websites", "Weddings", "Wednesdays",
		"Weeds", "Weekends", "Weeks", "Weights", "Welcomes", "Welfares",
		"WellBeings", "Wells", "Wests", "Wheat", "Wheels", "Whispers",
		"Wholes", "Widows", "Widths", "Wildlives", "Willingnesses",
		"Wills", "Windows", "Winds", "Wines", "Wings", "Winners", "Wins",
		"Winters", "Wires", "Wisdoms", "Wishes", "Withdrawals", "Witnesses",
		"Wits", "Wonders", "Woods", "Wools", "Words", "Workers", "Workforces",
		"Workouts", "Workplaces", "Works", "Workshops", "Worlds", "Worms",
		"Worries", "Worses", "Worships", "Worsts", "Worths", "Wounds", "Wrists",
		"Writers", "Writings", "Wrongs", "Yards", "Years", "Yellows",
		"Yesterdays", "Yields", "Zones",
		"Implementations", "Implications", "Importances", "Imports",
		"Impressions", "Imprisonments", "Improvements", "Inabilities",
		"Incentives", "Inches", "Incidences", "Incidents", "Inclusions",
		"Incomes", "Increases", "Independences", "Indications", "Indicators",
		"Indices", "Indictments", "Individuals", "Industries", "Inequalities",
		"Infections", "Inflations", "Influences", "Information",
		"Infos", "Infrastructures", "Ingredients", "Inhabitants", "Initiatives",
		"Injections", "Injuries", "Injustices", "Inks",
		"Innovations", "Inputs", "Inquiries", "Insects", "Insertions",
		"Insiders", "Insides", "Insights", "Inspections", "Inspectors",
		"Inspirations", "Installations", "Instances", "Instincts", "Institutes",
		"Institutions", "Instructions", "Instructors", "Instruments", "Insults",
		"Insurances", "Intakes", "Integrations", "Integrities", "Intellectuals",
		"Intelligences", "Intensities", "Intentions", "Intents", "Interactions",
		"Interests", "Interfaces", "Interferences", "Interiors",
		"Interpretations", "Intervals", "Interventions", "Interviews",
		"Introductions", "Invasions", "Inventions", "Investigations",
		"Investigators", "Investments", "Investors", "Invitations",
		"Involvements", "Ironies", "Irons", "Islands", "Isolations", "Issues",
		"Items", "Its", "Jackets", "Jails", "Jams", "Januaries", "Jazzes",
		"Jeans", "Jets", "Jewelleries", "Jobs", "Joints", "Jokes",
		"Journalisms", "Journalists", "Journals", "Journeys", "Joys",
		"Judgements", "Judges", "Juices", "Julies", "Jumps", "Junctions",
		"Junes", "Juries", "Jurisdictions", "Justices", "Justifications",
		"Keyboards", "Keys", "Kicks", "Kidneys", "Kilometres",
		"Kinds", "Kingdoms", "Kings", "Kisses", "Kitchens", "Kits", "Knees",
		"Knives", "Knocks", "Knowledges", "Labels", "Laboratories", "Labours",
		"Labs", "Lacks", "Ladders", "Lakes", "Lamps",
		"Landings", "Landlords", "Landmarks", "Lands", "Landscapes", "Lanes",
		"Languages", "Laps", "Laptops", "Lasers", "Lasts", "Latests", "Laughs",
		"Laughters", "Launches", "Lawns", "Laws", "Lawsuits", "Lawyers",
	}
}

func nounOne() []string {
	return []string{
		"Rivals", "Rivers", "Roads", "Robberies", "Robots", "Rockets", "Rocks",
		"Rods", "Roles", "Rolls", "Romances", "Roofs", "Rooms", "Roots",
		"Ropes", "Roses", "Rotations", "Rounds", "Routes", "Routines", "Rows",
		"Rubbers", "Rubbishes", "Rugbies", "Ruins", "Rules", "Rulings",
		"Rumours", "Runners", "Runnings", "Runs", "Rushes", "Sacrifices",
		"Safeties", "Sailings", "Sailors", "Sails", "Saints", "Sakes", "Salads",
		"Salaries", "Sales", "Salts", "Samples", "Sanctions", "Sands",
		"Sandwiches", "Satellites", "Satisfactions", "Saturdays", "Sauces",
		"Savings", "Says", "Scales", "Scandals", "Scares", "Scenarios",
		"Scenes", "Schedules", "Schemes", "Scholars", "Scholarships", "Schools",
		"Sciences", "Scientists", "Scopes", "Scores", "Scratches", "Screams",
		"Screenings", "Screens", "Screws", "Scripts", "Scrutinies",
		"Sculptures", "Seals", "Searches", "Seas", "Seasons", "Seats",
		"Seconds", "Secretaries", "Secrets", "Sections", "Sectors",
		"Securities", "Seeds", "Seekers", "Segments", "Selections", "Selves",
		"Seminars", "Senators", "Sensations", "Senses", "Sensitivities",
		"Sentences", "Sentiments", "Separations", "Septembers", "Sequences",
		"Series", "Servants", "Services", "Sessions", "SetUps", "Sets",
		"Settings", "Settlements", "Settlers", "Shades",
		"Shadows", "Shakes", "Shames", "Shapes", "Shareholders", "Shares",
		"Sheep", "Sheets", "Shells", "Shelters", "Shelves", "Shifts",
		"Shippings", "Ships", "Shirts", "Shocks", "Shoes", "Shootings",
		"Shoots", "Shoppings", "Shops", "Shores", "Shortages", "Shots",
		"Shoulders", "Shouts", "Showers", "Shows", "Siblings", "Sides", "Sighs",
		"Sights", "Signals", "Signatures", "Significances", "Signs", "Silences",
		"Silks", "Silver", "Similarities", "Simulations", "Singers", "Singings",
		"Singles", "Sins", "Sirs", "Sites", "Situations", "Sizes",
		"Sketches", "Skies", "Skiings", "Skills", "Skins", "Skirts", "Skis",
		"Skulls", "Sleeps", "Slices", "Slides",
		"Slogans", "Slopes", "Slots", "Smartphones", "Smells", "Smiles",
		"Smokes", "Smokings", "Snakes", "Snows", "Soaps", "Soccers",
		"Societies", "Socks", "Softwares", "Soils", "Soldiers", "Solicitors",
		"Solidarities", "Solids", "Solos", "Solutions", "Songs", "Sons",
		"Sorts", "Souls", "Sounds", "Soups", "Sources",
		"Sovereignties", "Spaces", "Spams", "Spans", "Speakers", "Specialists",
		"Species", "Specifications", "Specimens", "Spectacles", "Spectators",
		"Spectra", "Speculations", "Speeches", "Speeds", "Spellings", "Spells",
		"Spendings", "Spheres", "Spices", "Spiders", "Spies", "Spines", "Spins",
		"Spirits", "Spites", "Splits", "Spokesmen", "Spokespeople", "Sponsors",
		"Sponsorships", "Spoons", "Sports", "Spotlights", "Spots", "Spouses",
		"Spreads", "Springs", "Squads", "Squares", "Stabilities", "Stadiums",
		"Staffs", "Stages", "Stairs", "Stakes", "Stalls", "Stamps", "Stances",
		"Standards", "Stands", "Stars", "Starts", "Statements", "States",
		"Stations", "Statistics", "Statues", "Status", "Stays", "Steams",
		"Steels", "Stems", "Steps", "Stereotypes", "Sticks", "Stimuli",
		"Stocks", "Stomachs", "Stones", "Stops", "Storages", "Stores",
		"Stories", "Storms", "Strains", "Strands", "Strangers", "Strategies",
		"Streams", "Streets", "Strengths", "Stresses", "Stretches", "Strikes",
		"Strings", "Strips", "Strokes", "Structures", "Struggles", "Students",
		"Studies", "Studios", "Stuffs", "Styles", "Subjects", "Submissions",
		"Subscribers", "Subscriptions", "Subsidies", "Substances",
		"Substitutes", "Substitutions", "Suburbs", "Successes", "Successions",
		"Successors", "Sufferings", "Sugars", "Suggestions",
		"Suites", "Suits", "Summaries", "Summers", "Summits", "Sums", "Sundays",
		"Suns", "Supermarkets", "Supervisions", "Supervisors", "Supplements",
		"Supplies", "Supporters", "Supports", "Surfaces", "Surgeons",
		"Surgeries", "Surges", "Surplus", "Surprises", "Surveillances",
		"Surveys", "Survivals", "Survivors", "Suspects", "Suspensions",
		"Suspicions", "Sweaters", "Sweets", "Swimmings", "Swims", "Swings",
		"Switches", "Swords", "Symbols", "Sympathies", "Symptoms", "Syndromes",
		"Syntheses", "Systems", "TShirts", "Tables", "Tablets", "Tackles",
		"Tactics", "Tags", "Tails", "Talents", "Tales", "Talks", "Tanks",
		"Tapes", "Taps", "Targets", "Tasks", "Tastes", "Taxes", "Taxis",
		"Taxpayers", "Teachers", "Teachings", "Teams", "Tears", "Teas",
		"Techniques", "Technologies", "Teenagers", "Teens", "Teeth",
		"Telephones", "Televisions", "Temperatures", "Temples", "Tenants",
		"Tendencies", "Tennis", "Tensions", "Tents", "Tenures", "Terminals",
		"Terms", "Terrains", "Territories",
		"Testimonies", "Testings", "Tests", "Textbooks", "Texts",
		"Textures", "Thanks", "Theatres", "Thefts", "Themes", "Theologies",
		"Theories", "Therapies", "Therapists", "Theses", "Thieves", "Things",
		"Thinkings", "Thirds", "Thoughts", "Threads", "Threats", "Thresholds",
		"Throats", "Thumbs", "Thursdays", "Tickets", "Tides", "Ties", "Timbers",
		"Times", "Timings", "Tins", "Tips", "Tissues", "Titles", "Tobaccos",
		"Todays", "Toes", "Toilets", "Tolerances", "Tolls", "Tomatoes",
		"Tomorrows", "Tones", "Tongues", "Tonights", "Tonnes", "Tons", "Tools",
		"Topics", "Tops", "Tortoises", "Totals", "Touches", "Tourisms",
		"Tourists", "Tournaments", "Tours", "Towels", "Towers", "Towns", "Toys",
	}
}

func nounSix() []string {
	return []string{
		"Certainties", "Certificates", "Chains", "Chairmen", "Chairs",
		"Challenges", "Chambers", "Champions", "Championships", "Chances",
		"Changes", "Channels", "Chaos", "Chapters", "Characteristics",
		"Characters", "Charges", "Charities", "Charms", "Charters", "Charts",
		"Chases", "Chats", "Cheats", "Checks", "Cheeks", "Cheers", "Cheeses",
		"Chefs", "Chemicals", "Chemistries", "Chests", "Chickens", "Chiefs",
		"Childhoods", "Chips", "Chocolates", "Choices", "Choirs", "Chunks",
		"Churches", "Cigarettes", "Cinemas", "Circles", "Circuits",
		"Circulations", "Circumstances", "Cities", "Citizens", "Citizenships",
		"Civilians", "Civilizations", "Claims", "Clarities", "Clashes",
		"Classes", "Classics", "Classifications", "Classrooms", "Clauses",
		"Clerks", "Clicks", "Clients", "Cliffs", "Climates", "Climbs",
		"Clinics", "Clips", "Clocks", "Closes", "Closures", "Clothes",
		"Clothings", "Cloths", "Clouds", "Clubs", "Clues", "Clusters",
		"Coaches", "Coalitions", "Coals", "Coasts", "Coats", "Cocktails",
		"Codes", "Coffees", "Coincidences", "Coins", "Colds", "Collaborations",
		"Collapses", "Colleagues", "Collections", "Collectors", "Colleges",
		"Collisions", "Colonies", "Colours", "Columnists", "Columns", "Combats",
		"Combinations", "Comedies", "Comforts", "Comics", "Commanders",
		"Commands", "Commentaries", "Commentators", "Comments", "Commerces",
		"Commercials", "Commissioners", "Commissions", "Commitments",
		"Committees", "Commodities", "Communications", "Communities",
		"Companies", "Companions", "Comparisons", "Compassions",
		"Compensations", "Competences", "Competitions", "Competitors",
		"Complaints", "Completions", "Complexes", "Complexities", "Compliances",
		"Complications", "Components", "Composers", "Compositions", "Compounds",
		"Compromises", "Computers", "Concentrations", "Conceptions", "Concepts",
		"Concerns", "Concerts", "Concessions", "Conclusions", "Concretes",
		"Conditions", "Conducts", "Conferences", "Confessions", "Confidences",
		"Configurations", "Confirmations", "Conflicts", "Confrontations",
		"Confusions", "Congregations", "Connections", "Consciences",
		"Consciousnesses", "Consensus", "Consents", "Consequences",
		"Conservations", "Conservatives", "Considerations", "Consistencies",
		"Conspiracies", "Constituencies", "Constitutions", "Constraints",
		"Constructions", "Consultants", "Consultations", "Consumers",
		"Consumptions", "Contacts", "Containers", "Contempts", "Contenders",
		"Contentions", "Contents", "Contests", "Contexts", "Continents",
		"Contractors", "Contracts", "Contradictions", "Contraries", "Contrasts",
		"Contributions", "Contributors", "Controls", "Controversies",
		"Conveniences", "Conventions", "Conversations", "Conversions",
		"Convictions", "Cookers", "Cookings", "Cooks", "Coordinations",
		"Coordinators", "Copies", "Coppers", "Cops", "Copyrights", "Cores",
		"Corners", "Corporations", "Corrections", "Correlations",
		"Correspondences", "Correspondents", "Corridors", "Corruptions",
		"Costs", "Costumes", "Cottages", "Cottons", "Councillors", "Councils",
		"Counsellings", "Counsellors", "Counterparts", "Counters", "Counties",
		"Countries", "Countrysides", "Counts", "Couples", "Coups", "Courages",
		"Courses", "Courtesies", "Courts", "Cousins", "Coverages", "Covers",
		"Cows", "Cracks", "Crafts", "Crashes", "Creams", "Creations",
		"Creativities", "Creators", "Creatures", "Credibilities", "Credits",
		"Crews", "Cries", "Crises", "Criteria",
		"Criticisms", "Critics", "Critiques", "Crops", "Crosses", "Crowds",
		"Crowns", "Cruises", "Crystals", "Cues", "Cults", "Cultures",
		"Cupboards", "Cups", "Cures", "Curiosities", "Currencies", "Currents",
		"Curricula", "Curtains", "Custodies", "Customers", "Customs",
		"Greenhouses", "Greens", "Greys", "Grids", "Griefs", "Grins", "Grips",
		"Groceries", "Grounds", "Groups", "Growths", "Guarantees", "Guards",
		"Guerrillas", "Guesses", "Guests", "Guidances", "Guidelines", "Guides",
		"Guilts", "Guitars", "Guts", "Guys", "Gyms", "Habitats",
		"Habits", "Hairs", "Halls", "Halts", "Halves", "Handfuls", "Handles",
		"Handlings", "Hands", "Happinesses", "Harassments", "Harbours",
		"Hardwares", "Harmonies", "Harms", "Harvests",
		"Hats", "Hazards", "Headaches", "Headlines", "Headquarters", "Heads",
		"Healthcares", "Healths", "Hearings", "Hearts", "Heatings", "Heats",
		"Heavens", "Heels", "Heights", "Helicopters", "Hellos", "Hells",
		"Helmets", "Helps", "Herbs", "Heritages", "Heroes", "Hierarchies",
		"Highlights", "Highs", "Highways", "Hills", "Hints", "Hips", "Hires",
		"Historians", "Histories", "Hits", "Hobbies", "Hockeys", "Holds",
		"Holes", "Holidays", "Homelands", "Homes", "Homework", "Honesties",
		"Honours", "Hooks", "Hopes", "Horizons", "Horns", "Horrors", "Horses",
		"Hospitals", "Hosts", "Hotels", "Hours",
		"Households", "Houses", "Housings", "Humanities", "Humans", "Humours",
	}
}

func nounFour() []string {
	return []string{
		"Abilities", "Absences", "Abundances", "Academics",
		"Academies", "Accents", "Acceptances", "Accesses", "Accidents",
		"Accommodations", "Accomplishments", "Accordances", "Accountabilities",
		"Accountants", "Accounts", "Accumulations", "Accuracies", "Accusations",
		"Accused", "Achievements", "Acids", "Acquisitions", "Acres", "Actions",
		"Activations", "Activists", "Activities", "Actors", "Actresses", "Acts",
		"Adaptations", "Addictions", "Additions", "Addresses", "Adjustments",
		"Administrations", "Administrators", "Admissions", "Adolescents",
		"Adoptions", "Ads", "Adults", "Advances", "Advantages", "Adventures",
		"Advertisements", "Advertisings", "Advice", "Advocates", "Affairs",
		"Affections", "Aftermaths", "Afternoons", "Agencies", "Agendas",
		"Agents", "Ages", "Aggressions", "Agreements", "Agricultures", "Aides",
		"Alarms", "Albums", "Alerts", "Aliens", "Alignments",
		"Allegations", "Alliances", "Allies", "Allocations", "Allowances",
		"Alternatives", "Aluminium", "Amateurs", "Ambassadors", "Ambitions",
		"Ambulances", "Amendments", "Amounts", "Analogies", "Analyses",
		"Analysts", "Ancestors", "Anchors", "Angels", "Angers", "Angles",
		"Animals", "Animations", "Ankles", "Anniversaries", "Announcements",
		"Answers", "Anxieties", "Apartments", "Apologies", "Apparatus",
		"Appeals", "Appearances", "Appetites", "Apples", "Applicants",
		"Applications", "Appointments", "Appreciations", "Approaches",
		"Approvals", "Apps", "Aprils", "Architects", "Architectures",
		"Archives", "Areas", "Arenas", "Arguments", "Armies",
		"Arrangements", "Arrays", "Arrests", "Arrivals", "Arrows", "Articles",
		"Artists", "Arts", "Artworks", "Ashes", "Aspects", "Aspirations",
		"Assaults", "Assemblies", "Assertions", "Assessments",
		"Assets", "Assignments", "Assistances", "Assistants", "Associations",
		"Assumptions", "Assurances", "Asylums", "Athletes", "Atmospheres",
		"Attachments", "Attacks", "Attempts", "Attendances",
		"Attentions", "Attitudes", "Attorneys", "Attractions", "Attributes",
		"Auctions", "Audiences", "Audits", "Augusts", "Aunts", "Authorities",
		"Authors", "Autonomies", "Autos", "Autumns", "Availabilities",
		"Averages", "Awards", "Awarenesses", "Babies", "Backdrops",
		"Backgrounds", "Backings", "Backs", "Backups", "Bacterias", "Badges",
		"Bags", "Bails", "Balances", "Ballets", "Balloons", "Ballots", "Balls",
		"Bananas", "Bands", "Banks", "Banners", "Bans", "Bargains", "Barrels",
		"Barriers", "Bars", "Baseballs", "Basements", "Bases",
		"Basketballs", "Baskets", "Basses", "Bathrooms", "Baths", "Bats",
		"Batteries", "Battlefields", "Battles", "Bays", "Beaches", "Beams",
		"Beans", "Bears", "Beasts", "Beats", "Beauties", "Bedrooms", "Beds",
		"Beefs", "Beers", "Bees", "Beginnings", "Behalves", "Behaviours",
		"Beings", "Beliefs", "Bells", "Belts", "Benches", "Benchmarks", "Bends",
		"Beneficiaries", "Benefits", "Bests", "Bets", "Betters", "Biases",
		"Bicycles", "Bids", "Bikes", "Bills", "Bins", "Biographies",
		"Biologies", "Birds", "Birthdays", "Births", "Biscuits", "Bishops",
		"Bites", "Bits", "Blades", "Blames", "Blankets", "Blanks",
		"Blasts", "Blends", "Blessings", "Blocks", "Blogs", "Bloods", "Blows",
		"Blues", "Boards", "Boats", "Bonds",
		"Bones", "Bonus", "Bookings", "Books", "Booms", "Boosts", "Boots",
		"Borders", "Bosses", "Bottles", "Boundaries", "Bowls",
		"Bows", "Boxes", "Brains", "Branches", "Brands",
		"Breaches", "Breads", "Breakdowns", "Breakfasts", "Breaks",
		"Breakthroughs", "Breathings", "Breaths", "Breeds",
		"Brethren", "Bricks", "Brides", "Bridges", "Broadbands", "Broadcasters",
		"Broadcasts", "Browsers", "Brushes", "Bubbles", "Bucks",
		"Buddies", "Budgets", "Buffers", "Bugs", "Buildings", "Bulks",
		"Bullets", "Bunches", "Burdens", "Bureaucracies", "Burials", "Burns",
		"Buses", "Bushes", "Businesses", "Businessmen", "Butters", "Buttons",
		"Cabinets", "Cabins", "Cables", "Cafes", "Cakes", "Calculations",
		"Calls", "Calms", "Cameras", "Campaigns", "Campings", "Camps", "Campus",
		"Canals", "Candidates", "Candles", "Cans", "Canvas",
		"Capabilities", "Capacities", "Capitalisms", "Capitals", "Caps",
		"Captains", "Captures", "Carbons", "Cards", "Careers", "Cares",
		"Cargoes", "Carpets", "Carriages", "Carrots", "Cars", "Cartoons",
		"Cases", "Cashes", "Casinos", "Castles", "Casts",
		"Catalogues", "Catches", "Categories", "Cats", "Cattle", "Causes",
		"Cautions", "Caves", "Cds", "Ceilings", "Celebrations", "Celebrities",
		"Cells", "Cemeteries", "Centres", "Cents", "Centuries", "Ceremonies",
	}
}
