package manifest

func PluralNoun() []string {
	noun := make([]string, 0)
	for _, fn := range []strSliceFnT{nounFour, noundThree, nounTwo, nounOne, nounFive, nounSix, nounSeven} {
		noun = append(noun, fn()...)
	}

	return noun
}

func nounSeven() []string {
	return []string{
		"Registers", "Registrations", "Regrets", "Regulations", "Regulators",
		"Rehabilitations", "Reigns", "Rejections", "Relations", "Relationships",
		"Relatives", "Releases", "Relevances", "Reliabilities", "Reliefs",
		"Religions", "Remainders", "Remains", "Remarks", "Remedies",
		"Reminders", "Removals", "Rentals", "Rents", "Repairs", "Repeats",
		"Replacements", "Replies", "Reporters", "Reportings", "Reports",
		"Representations", "Representatives", "Reproductions", "Republics",
		"Reputations", "Requests", "Requirements", "Rescues", "Researchers",
		"Researches", "Reservations", "Reserves", "Residences", "Residents",
		"Residues", "Resignations", "Resistances", "Resolutions", "Resorts",
		"Resources", "Respects", "Responses", "Responsibilities", "Restaurants",
		"Restorations", "Restraints", "Restrictions", "Rests", "Results",
		"Retails", "Retirements", "Retreats", "Returns", "Revelations",
		"Revenges", "Revenues", "Reverses", "Reviews", "Revisions", "Revivals",
		"Revolutions", "Rewards", "Rhetorics", "Rhythms", "Rices", "Rides",
		"Rifles", "Rights", "Rings", "Riots", "Rises", "Risks", "Rituals",
		"Documentations", "Documents", "Dogs", "Dollars", "Domains",
		"Dominances", "Donations", "Donors", "Doors", "Doses", "Dots", "Doubts",
		"Downloads", "Downtowns", "Dozens", "Drafts", "Dramas", "Drawings",
		"Dreams", "Dresses", "Drinks", "Drivers", "Drives", "Drivings", "Drops",
		"Droughts", "Drums", "Duos", "Durations", "Dusts", "Duties",
		"Dvds", "Dynamics", "Earnings", "Ears", "Earthquakes", "Earths",
		"Eases", "Easts", "Echoes", "Economics", "Economies", "Economists",
		"Edges", "Editions", "Editors", "Educations", "Educators",
		"Effectivenesses", "Effects", "Efficiencies", "Efforts", "Eggs", "Egos",
		"Elbows", "Elections", "Electricities", "Electronics", "Elements",
		"Elephants", "Elites", "Emails", "Embarrassments", "Embassies",
		"Emergences", "Emergencies", "Emissions", "Emotions", "Emphases",
		"Empires", "Employees", "Employers", "Employments", "Encounters",
		"Encouragements", "Endeavours", "Endings", "Endorsements", "Ends",
		"Enemies", "Energies", "Enforcements", "Engagements", "Engineerings",
		"Engineers", "Engines", "Enquiries", "Enterprises", "Entertainments",
		"Enthusiasms", "Enthusiasts", "Entities", "Entrances", "Entrepreneurs",
		"Entries", "Envelopes", "Environments", "Epidemics", "Episodes",
		"Equalities", "Equals", "Equations", "Equipment", "Equivalents", "Eras",
		"Errors", "Escapes", "Essays", "Essences", "Establishments", "Estates",
		"Estimates", "Ethics", "Euros", "Evaluations", "Evenings", "Events",
		"Evidence", "Evils", "Evolutions", "Examinations", "Examples", "Exams",
		"Excellences", "Exceptions", "Excesses", "Exchanges", "Excitements",
		"Exclusions", "Excuses", "Executives", "Exercises",
		"Exhibitions", "Exhibits", "Exiles", "Existences", "Exits",
		"Expansions", "Expectations", "Expeditions", "Expenditures", "Expenses",
		"Experiences", "Experiments", "Expertises", "Experts", "Explanations",
		"Exploitations", "Explorations", "Explosions", "Explosives", "Exports",
		"Exposures", "Expressions", "Extensions", "Extents", "Extracts",
		"Extras", "Extremes", "Eyes", "Fabrics", "Faces",
		"Facilities", "Factions", "Factories", "Factors", "Facts", "Faculties",
		"Failures", "Fairnesses", "Faiths", "Falls", "Fames", "Families",
		"Fans", "Fantasies", "Fares", "Farmers", "Farmings", "Farms",
		"Fashions", "Fates", "Fats", "Faults", "Favourites", "Favours", "Fears",
		"Feathers", "Feats", "Features", "Februaries", "Feedbacks", "Feeds",
		"Feelings", "Feels", "Fees", "Feet", "Feminists", "Fences",
		"Festivals", "Fevers", "Fibres", "Fictions", "Fields", "Fighting",
		"Fights", "Figures", "Files", "FilmMakers", "Films", "Filters",
		"Finals", "Finances", "Findings", "Fines", "Fingers", "Finishes",
		"Firefighters", "Fires", "Fireworks", "Firms", "Firsts",
		"Fish", "Fishings", "Fitnesses", "Fits", "Fixes", "Fixtures", "Flags",
		"Flames", "Flashes", "Flats", "Flavours", "Flaws", "Fleets", "Fleshes",
		"Flexibilities", "Flies", "Flights", "Floods", "Floors", "Flours",
		"Flowers", "Flows", "Fluids", "Flus", "Flyings", "Foci", "Folds",
		"Folks", "Followings", "Foods", "Fools", "Footages", "Footballs",
		"Forces", "Forecasts", "Foreigners", "Forests", "Forks", "Formations",
		"Formats", "Forms", "Formulae", "Fortunes", "Forums", "Fossils",
		"Foundations", "Founders", "Fractions", "Fragments", "Frames",
		"Frameworks", "Franchises", "Frauds", "Freedoms", "Frequencies",
		"Fridays", "Fridges", "Friends", "Friendships", "Frogs", "Fronts",
		"Fruits", "Frustrations", "Fuels", "Functions", "Fundings",
		"Fundraisings", "Funds", "Funerals", "Funs", "Furnitures", "Furs",
		"Futures", "Gains", "Galleries", "Gallons", "Gamblings", "Games",
		"Gamings", "Gaps", "Garages", "Gardens", "Gases", "Gates",
		"Gatherings", "Gazes", "Gears", "Genders", "Generations", "Genes",
		"Genius", "Genres", "Gentlemen", "Geographies", "Gestures",
		"Ghosts", "Giants", "Gifts", "Gigs", "Glances", "Glasses", "Glimpses",
		"Globalizations", "Globes", "Glories", "Gloves", "Goals", "Gods",
		"Goes", "Gold", "Golfs", "Goodbyes", "Goodnesses", "Goods",
		"Governances", "Governments", "Governors", "Graces", "Grades",
		"Graduates", "Grains", "Grandfathers", "Grandmothers", "Grandparents",
		"Grants", "Graphics", "Grasps", "Grasses", "Graves", "Gravities",
	}
}

func nounFive() []string {
	return []string{
		"Placements", "Places", "Planes", "Planets", "Plannings", "Plans",
		"Plants", "Plastics", "Plates", "Platforms", "Players", "Plays",
		"Pleas", "Pleasures", "Pledges", "Plots", "Plugs", "Plus", "Pockets",
		"Poems", "Poetries", "Poets", "Points", "Poisons", "Poles", "Police",
		"Policemen", "Policies", "Politicians", "Politics", "Polls",
		"Pollutions", "Ponds", "Pools", "Pops", "Popularities", "Populations",
		"Portfolios", "Portions", "Portraits", "Ports", "Positions",
		"Positives", "Possessions", "Possibilities", "Posters", "Posts",
		"Potatoes", "Potentials", "Pots", "Pounds", "Poverties", "Powders",
		"Powers", "Practices", "Practitioners", "Praises", "Prayers",
		"Precedents", "Precisions", "Predators", "Predecessors", "Predictions",
		"Preferences", "Pregnancies", "Prejudices", "Premises", "Premiums",
		"Preparations", "Prescriptions", "Presences", "Presentations",
		"Presents", "Preservations", "Presidencies", "Presidents", "Presses",
		"Pressures", "Prevalences", "Preventions", "Preys", "Prices", "Prides",
		"Priests", "Princes", "Princesses", "Principals", "Principles",
		"Printers", "Printings", "Prints", "Priorities", "Prisons",
		"Privacies", "Privatizations", "Privileges", "Prizes", "Probabilities",
		"Probes", "Problems", "Procedures", "Proceedings", "Proceeds",
		"Processes", "Processings", "Processors", "Producers", "Produces",
		"Productions", "Productivities", "Products", "Professionals",
		"Professions", "Professors", "Profiles", "Profits", "Programmes",
		"Programmings", "Programs", "Progresses", "Projections", "Projects",
		"Promises", "Promotions", "Proofs", "Propagandas", "Properties",
		"Proportions", "Proposals", "Propositions", "Prosecutions",
		"Prosecutors", "Prospects", "Prosperities", "Protections", "Proteins",
		"Protesters", "Protests", "Protocols", "Provinces", "Provisions",
		"Psychologies", "Psychologists", "Publications", "Publicities",
		"Publics", "Publishings", "Pubs", "Pulls", "Pulses", "Pumps", "Punches",
		"Punishments", "Punks", "Pupils", "Purchases", "Purples", "Purposes",
		"Pursuits", "Pushes", "Puzzles", "Qualifications", "Qualities",
		"Quantities", "Quarters", "Queens", "Queries", "Questionnaires",
		"Questions", "Quests", "Queues", "Quotas", "Quotations", "Quotes",
		"Races", "Racings", "Radars", "Radiations",
		"Radios", "Rages", "Raids", "Rails", "Railways", "Rains", "Rallies",
		"Ranges", "Rankings", "Ranks", "Rates", "Ratings", "Ratios",
		"Rats", "Rays", "Reaches", "Reactions", "Readers", "Readings",
		"Cuts", "Cuttings", "Cycles", "Dads", "Dairies", "Damages", "Dams",
		"Dancers", "Dances", "Dancings", "Dangers", "Darknesses", "Darks",
		"Databases", "Dates", "Daughters", "Dawns", "Days",
		"Deadlines", "Dealers", "Deals", "Debates", "Debris", "Debts",
		"Debuts", "Decades", "Decembers", "DecisionMakings", "Decisions",
		"Decks", "Declarations", "Declines", "Decorations", "Decreases",
		"Dedications", "Deeds", "Defaults", "Defeats", "Defects", "Defences",
		"Defenders", "Deficiencies", "Deficits", "Definitions", "Degrees",
		"Delays", "Delegates", "Delegations", "Delights", "Deliveries",
		"Demands", "Democracies", "Demons", "Demonstrations", "Denials",
		"Densities", "Dentists", "Departments", "Departures", "Dependences",
		"Deployments", "Deposits", "Depressions", "Depths", "Deputies",
		"Descents", "Descriptions", "Deserts", "Designers", "Designs",
		"Desires", "Desks", "Desktops", "Destinations", "Destructions",
		"Details", "Detections", "Detectives", "Detentions", "Determinations",
		"Developments", "Devices", "Devils", "Diagnoses", "Diagrams",
		"Dialogues", "Diamonds", "Diaries", "Dictators", "Dictionaries",
		"Diets", "Differences", "Difficulties", "Dignities", "Dilemmas",
		"Dimensions", "Dinners", "Diplomats", "Directions", "Directories",
		"Directors", "Dirts", "Disabilities", "Disadvantages", "Disagreements",
		"Disappointments", "Disciplines", "Disclosures",
		"Discounts", "Discourses", "Discoveries", "Discretions",
		"Discs", "Discussions", "Dishes",
		"Disks", "Dislikes", "Dismissals", "Disorders", "Displays", "Disposals",
		"Disputes", "Disruptions", "Distances", "Distinctions", "Distresses",
		"Distributions", "Districts", "Diversities", "Dives", "Divides",
		"Divisions", "Divorces", "Doctors", "Doctrines", "Documentaries",
		"Hungers", "Huntings", "Hunts", "Hurricanes", "Hurries", "Hurts",
		"Hydrogens", "Hypotheses", "Ices", "Icons", "Ideals", "Ideas",
		"Identifications", "Identities", "Ideologies", "Ids",
		"Ignorances", "Illusions", "Illustrations", "Imageries",
		"Images", "Imaginations", "Immigrations", "Impacts",
		"Realities", "Realizations", "Realms", "Rears", "Reasonings", "Reasons",
		"Rebellions", "Rebels", "Receipts", "Receivers", "Receptions",
		"Recessions", "Recipes", "Recipients", "Recognitions",
		"Recommendations", "Reconstructions", "Recordings", "Records",
		"Recoveries", "Recruitments", "Recruits", "Reductions",
		"Referees", "References", "Referendums", "Reflections", "Reforms",
		"Refusals", "Regards", "Regimes", "Regions",
	}
}

func nounSix() []string {
	return []string{
		"Certainties", "Certificates", "Chains", "Chairmen", "Chairs",
		"Challenges", "Chambers", "Champions", "Championships", "Chances",
		"Changes", "Channels", "Chaos", "Chapters", "Characteristics",
		"Characters", "Charges", "Charities", "Charms", "Charters", "Charts",
		"Chases", "Chats", "Cheats", "Checks", "Cheeks", "Cheers", "Cheeses",
		"Chefs", "Chemicals", "Chemistries", "Chests", "Chickens", "Chiefs",
		"Childhoods", "Chips", "Chocolates", "Choices", "Choirs", "Chunks",
		"Churches", "Cigarettes", "Cinemas", "Circles", "Circuits",
		"Circulations", "Circumstances", "Cities", "Citizens", "Citizenships",
		"Civilians", "Civilizations", "Claims", "Clarities", "Clashes",
		"Classes", "Classics", "Classifications", "Classrooms", "Clauses",
		"Clerks", "Clicks", "Clients", "Cliffs", "Climates", "Climbs",
		"Clinics", "Clips", "Clocks", "Closes", "Closures", "Clothes",
		"Clothings", "Cloths", "Clouds", "Clubs", "Clues", "Clusters",
		"Coaches", "Coalitions", "Coals", "Coasts", "Coats", "Cocktails",
		"Codes", "Coffees", "Coincidences", "Coins", "Colds", "Collaborations",
		"Collapses", "Colleagues", "Collections", "Collectors", "Colleges",
		"Collisions", "Colonies", "Colours", "Columnists", "Columns", "Combats",
		"Combinations", "Comedies", "Comforts", "Comics", "Commanders",
		"Commands", "Commentaries", "Commentators", "Comments", "Commerces",
		"Commercials", "Commissioners", "Commissions", "Commitments",
		"Committees", "Commodities", "Communications", "Communities",
		"Companies", "Companions", "Comparisons", "Compassions",
		"Compensations", "Competences", "Competitions", "Competitors",
		"Complaints", "Completions", "Complexes", "Complexities", "Compliances",
		"Complications", "Components", "Composers", "Compositions", "Compounds",
		"Compromises", "Computers", "Concentrations", "Conceptions", "Concepts",
		"Concerns", "Concerts", "Concessions", "Conclusions", "Concretes",
		"Conditions", "Conducts", "Conferences", "Confessions", "Confidences",
		"Configurations", "Confirmations", "Conflicts", "Confrontations",
		"Confusions", "Congregations", "Connections", "Consciences",
		"Consciousnesses", "Consensus", "Consents", "Consequences",
		"Conservations", "Conservatives", "Considerations", "Consistencies",
		"Conspiracies", "Constituencies", "Constitutions", "Constraints",
		"Constructions", "Consultants", "Consultations", "Consumers",
		"Consumptions", "Contacts", "Containers", "Contempts", "Contenders",
		"Contentions", "Contents", "Contests", "Contexts", "Continents",
		"Contractors", "Contracts", "Contradictions", "Contraries", "Contrasts",
		"Contributions", "Contributors", "Controls", "Controversies",
		"Conveniences", "Conventions", "Conversations", "Conversions",
		"Convictions", "Cookers", "Cookings", "Cooks", "Coordinations",
		"Coordinators", "Copies", "Coppers", "Cops", "Copyrights", "Cores",
		"Corners", "Corporations", "Corrections", "Correlations",
		"Correspondences", "Correspondents", "Corridors", "Corruptions",
		"Costs", "Costumes", "Cottages", "Cottons", "Councillors", "Councils",
		"Counsellings", "Counsellors", "Counterparts", "Counters", "Counties",
		"Countries", "Countrysides", "Counts", "Couples", "Coups", "Courages",
		"Courses", "Courtesies", "Courts", "Cousins", "Coverages", "Covers",
		"Cows", "Cracks", "Crafts", "Crashes", "Creams", "Creations",
		"Creativities", "Creators", "Creatures", "Credibilities", "Credits",
		"Crews", "Cries", "Crises", "Criteria",
		"Criticisms", "Critics", "Critiques", "Crops", "Crosses", "Crowds",
		"Crowns", "Cruises", "Crystals", "Cues", "Cults", "Cultures",
		"Cupboards", "Cups", "Cures", "Curiosities", "Currencies", "Currents",
		"Curricula", "Curtains", "Custodies", "Customers", "Customs",
		"Greenhouses", "Greens", "Greys", "Grids", "Griefs", "Grins", "Grips",
		"Groceries", "Grounds", "Groups", "Growths", "Guarantees", "Guards",
		"Guerrillas", "Guesses", "Guests", "Guidances", "Guidelines", "Guides",
		"Guilts", "Guitars", "Guts", "Guys", "Gyms", "Habitats",
		"Habits", "Hairs", "Halls", "Halts", "Halves", "Handfuls", "Handles",
		"Handlings", "Hands", "Happinesses", "Harassments", "Harbours",
		"Hardwares", "Harmonies", "Harms", "Harvests",
		"Hats", "Hazards", "Headaches", "Headlines", "Headquarters", "Heads",
		"Healthcares", "Healths", "Hearings", "Hearts", "Heatings", "Heats",
		"Heavens", "Heels", "Heights", "Helicopters", "Hellos", "Hells",
		"Helmets", "Helps", "Herbs", "Heritages", "Heroes", "Hierarchies",
		"Highlights", "Highs", "Highways", "Hills", "Hints", "Hips", "Hires",
		"Historians", "Histories", "Hits", "Hobbies", "Hockeys", "Holds",
		"Holes", "Holidays", "Homelands", "Homes", "Homework", "Honesties",
		"Honours", "Hooks", "Hopes", "Horizons", "Horns", "Horrors", "Horses",
		"Hospitals", "Hosts", "Hotels", "Hours",
		"Households", "Houses", "Housings", "Humanities", "Humans", "Humours",
	}
}

func nounFour() []string {
	return []string{
		"Abilities", "Absences", "Abundances", "Academics",
		"Academies", "Accents", "Acceptances", "Accesses", "Accidents",
		"Accommodations", "Accomplishments", "Accordances", "Accountabilities",
		"Accountants", "Accounts", "Accumulations", "Accuracies", "Accusations",
		"Accused", "Achievements", "Acids", "Acquisitions", "Acres", "Actions",
		"Activations", "Activists", "Activities", "Actors", "Actresses", "Acts",
		"Adaptations", "Addictions", "Additions", "Addresses", "Adjustments",
		"Administrations", "Administrators", "Admissions", "Adolescents",
		"Adoptions", "Ads", "Adults", "Advances", "Advantages", "Adventures",
		"Advertisements", "Advertisings", "Advice", "Advocates", "Affairs",
		"Affections", "Aftermaths", "Afternoons", "Agencies", "Agendas",
		"Agents", "Ages", "Aggressions", "Agreements", "Agricultures", "Aides",
		"Alarms", "Albums", "Alerts", "Aliens", "Alignments",
		"Allegations", "Alliances", "Allies", "Allocations", "Allowances",
		"Alternatives", "Aluminium", "Amateurs", "Ambassadors", "Ambitions",
		"Ambulances", "Amendments", "Amounts", "Analogies", "Analyses",
		"Analysts", "Ancestors", "Anchors", "Angels", "Angers", "Angles",
		"Animals", "Animations", "Ankles", "Anniversaries", "Announcements",
		"Answers", "Anxieties", "Apartments", "Apologies", "Apparatus",
		"Appeals", "Appearances", "Appetites", "Apples", "Applicants",
		"Applications", "Appointments", "Appreciations", "Approaches",
		"Approvals", "Apps", "Aprils", "Architects", "Architectures",
		"Archives", "Areas", "Arenas", "Arguments", "Armies",
		"Arrangements", "Arrays", "Arrests", "Arrivals", "Arrows", "Articles",
		"Artists", "Arts", "Artworks", "Ashes", "Aspects", "Aspirations",
		"Assaults", "Assemblies", "Assertions", "Assessments",
		"Assets", "Assignments", "Assistances", "Assistants", "Associations",
		"Assumptions", "Assurances", "Asylums", "Athletes", "Atmospheres",
		"Attachments", "Attacks", "Attempts", "Attendances",
		"Attentions", "Attitudes", "Attorneys", "Attractions", "Attributes",
		"Auctions", "Audiences", "Audits", "Augusts", "Aunts", "Authorities",
		"Authors", "Autonomies", "Autos", "Autumns", "Availabilities",
		"Averages", "Awards", "Awarenesses", "Babies", "Backdrops",
		"Backgrounds", "Backings", "Backs", "Backups", "Bacterias", "Badges",
		"Bags", "Bails", "Balances", "Ballets", "Balloons", "Ballots", "Balls",
		"Bananas", "Bands", "Banks", "Banners", "Bans", "Bargains", "Barrels",
		"Barriers", "Bars", "Baseballs", "Basements", "Bases",
		"Basketballs", "Baskets", "Basses", "Bathrooms", "Baths", "Bats",
		"Batteries", "Battlefields", "Battles", "Bays", "Beaches", "Beams",
		"Beans", "Bears", "Beasts", "Beats", "Beauties", "Bedrooms", "Beds",
		"Beefs", "Beers", "Bees", "Beginnings", "Behalves", "Behaviours",
		"Beings", "Beliefs", "Bells", "Belts", "Benches", "Benchmarks", "Bends",
		"Beneficiaries", "Benefits", "Bests", "Bets", "Betters", "Biases",
		"Bicycles", "Bids", "Bikes", "Bills", "Bins", "Biographies",
		"Biologies", "Birds", "Birthdays", "Births", "Biscuits", "Bishops",
		"Bites", "Bits", "Blades", "Blames", "Blankets", "Blanks",
		"Blasts", "Blends", "Blessings", "Blocks", "Blogs", "Bloods", "Blows",
		"Blues", "Boards", "Boats", "Bonds",
		"Bones", "Bonus", "Bookings", "Books", "Booms", "Boosts", "Boots",
		"Borders", "Bosses", "Bottles", "Boundaries", "Bowls",
		"Bows", "Boxes", "Brains", "Branches", "Brands",
		"Breaches", "Breads", "Breakdowns", "Breakfasts", "Breaks",
		"Breakthroughs", "Breathings", "Breaths", "Breeds",
		"Brethren", "Bricks", "Brides", "Bridges", "Broadbands", "Broadcasters",
		"Broadcasts", "Browsers", "Brushes", "Bubbles", "Bucks",
		"Buddies", "Budgets", "Buffers", "Bugs", "Buildings", "Bulks",
		"Bullets", "Bunches", "Burdens", "Bureaucracies", "Burials", "Burns",
		"Buses", "Bushes", "Businesses", "Businessmen", "Butters", "Buttons",
		"Cabinets", "Cabins", "Cables", "Cafes", "Cakes", "Calculations",
		"Calls", "Calms", "Cameras", "Campaigns", "Campings", "Camps", "Campus",
		"Canals", "Candidates", "Candles", "Cans", "Canvas",
		"Capabilities", "Capacities", "Capitalisms", "Capitals", "Caps",
		"Captains", "Captures", "Carbons", "Cards", "Careers", "Cares",
		"Cargoes", "Carpets", "Carriages", "Carrots", "Cars", "Cartoons",
		"Cases", "Cashes", "Casinos", "Castles", "Casts",
		"Catalogues", "Catches", "Categories", "Cats", "Cattle", "Causes",
		"Cautions", "Caves", "Cds", "Ceilings", "Celebrations", "Celebrities",
		"Cells", "Cemeteries", "Centres", "Cents", "Centuries", "Ceremonies",
	}
}
