package manifest

func verbOne() []string {
	return []string{
		"Manifest", "Manipulate", "Manufacture", "Map", "March", "Mark",
		"Market", "Marry", "Master", "Match", "Mate", "Matter", "Mature",
		"Maximize", "Mean", "Measure", "Meet", "Melt", "Mention", "Merge",
		"Mind", "Minimize", "Miss", "Mistake", "Mix", "Mobilize", "Model",
		"Modify", "Monitor", "Motivate", "Mount", "Move", "Multiply",
		"Name", "Narrow", "Need", "Neglect", "Negotiate", "Nod", "Nominate",
		"Note", "Notice", "Notify", "Number", "Obey", "Object", "Oblige",
		"Observe", "Obsess", "Obtain", "Occupy", "Occur", "Offend", "Offer",
		"Open", "Operate", "Oppose", "Opt", "Order", "Organize", "Originate",
		"Outline", "Outrage", "Overcome", "Overlook", "Oversee", "Overturn",
		"Overwhelm", "Owe", "Own", "Pace", "Pack", "Package", "Paint", "Park",
		"Participate", "Pass", "Patrol", "Pause", "Pay", "Perceive", "Perform",
		"Permit", "Persist", "Persuade", "Phone", "Photograph", "Pick",
		"Picture", "Pile", "Pin", "Pioneer", "Place", "Plan", "Plant", "Play",
		"Plead", "Please", "Pledge", "Plot", "Plug", "Plunge", "Point",
		"Pop", "Portray", "Pose", "Position", "Possess", "Post",
		"Postpone", "Pour", "Power", "Practise", "Praise", "Pray", "Preach",
		"Precede", "Predict", "Prefer", "Prepare", "Prescribe", "Present",
		"Preserve", "Preside", "Press", "Presume", "Pretend", "Prevail",
		"Prevent", "Price", "Print", "Probe", "Proceed", "Process", "Proclaim",
		"Produce", "Program", "Progress", "Prohibit", "Project", "Promise",
		"Promote", "Prompt", "Pronounce", "Propose", "Prosecute", "Protect",
		"Protest", "Prove", "Provide", "Provoke", "Publish", "Pull", "Pump",
		"Punch", "Punish", "Purchase", "Pursue", "Push", "Put", "Qualify",
		"Question", "Queue", "Quit", "Quote", "Race", "Raid", "Rain", "Raise",
		"Rally", "Range", "Rank", "Rate", "Reach", "React", "Read",
		"Realize", "Reassure", "Rebuild", "Recall", "Receive", "Reckon",
		"Recognize", "Recommend", "Record", "Recount", "Recover", "Recruit",
		"Recycle", "Reduce", "Refer", "Reflect", "Reform", "Refuse", "Regain",
		"Regard", "Register", "Regret", "Regulate", "Reign", "Reinforce",
		"Reject", "Relate", "Relax", "Release", "Relieve", "Rely", "Remain",
		"Remark", "Remember", "Remind", "Remove", "Render", "Renew", "Rent",
		"Repair", "Repeat", "Replace", "Reply", "Report", "Represent",
		"Reproduce", "Request", "Require", "Rescue", "Research", "Resemble",
		"Reserve", "Reside", "Resign", "Resist", "Resolve", "Respect",
		"Respond", "Rest", "Restore", "Restrict", "Result", "Resume", "Retain",
		"Retire", "Retreat", "Retrieve", "Return", "Reveal", "Reverse",
		"Review", "Revise", "Revive", "Reward", "Rid", "Ride", "Ring", "Rip",
		"Rise", "Risk", "Rob", "Rock", "Roll", "Rotate", "Rub", "Ruin", "Rule",
		"Run", "Rush", "Sack", "Sacrifice", "Sail", "Sample", "Satisfy", "Save",
		"Say", "Scan", "Scare", "Schedule", "Score", "Scratch", "Scream",
		"Screen", "Screw", "Seal", "Search", "Seat", "Secure", "See", "Seek",
		"Seize", "Select", "Sell", "Send", "Sense", "Sentence", "Separate",
		"Serve", "Set", "Settle", "Shake", "Shape", "Share", "Shatter", "Shed",
		"Shelter", "Shift", "Shine", "Ship", "Shock", "Shoot", "Shop", "Shout",
		"Show", "Shrink", "Shrug", "Shut", "Sigh", "Sign", "Signal", "Simulate",
		"Sing", "Sink", "Sit", "Ski", "Skip", "Slam", "Slap", "Slash", "Sleep",
		"Slice", "Slide", "Slip", "Slope", "Slow", "Smash", "Smell", "Smile",
		"Smoke", "Snap", "Snow", "Soak", "Soar", "Solve", "Sort", "Sound",
		"Span", "Spare", "Spark", "Speak", "Specialize", "Specify", "Speculate",
		"Speed", "Spell", "Spend", "Spill", "Spin", "Split", "Spoil", "Sponsor",
		"Spot", "Spread", "Spring", "Spy", "Squeeze", "Stab", "Stabilize",
		"Stage", "Stand", "Star", "Stare", "Start", "Starve", "State", "Stay",
		"Steal", "Steer", "Stem", "Step", "Stick", "Stimulate", "Stir", "Stop",
		"Store", "Strengthen", "Stress", "Stretch", "Strike", "Strip", "Strive",
		"Structure", "Struggle", "Study", "Stuff", "Stumble", "Stun", "Submit",
		"Substitute", "Succeed", "Sue", "Suffer", "Suggest", "Suit",
		"Sum", "Summarize", "Supervise", "Supplement", "Supply", "Support",
		"Suppose", "Suppress", "Surge", "Surprise", "Surrender", "Surround",
		"Survey", "Survive", "Suspect", "Suspend", "Sustain", "Swallow",
		"Swear", "Sweep", "Swim", "Swing", "Switch", "Tackle", "Tag", "Take",
		"Talk", "Tap", "Target", "Taste", "Tax", "Teach", "Tear", "Telephone",
		"Tell", "Tempt", "Tend", "Term", "Terminate", "Terrify", "Test",
		"Testify", "Text", "Thank", "Think", "Thrive", "Throw",
		"Tidy", "Tie", "Tighten", "Time", "Tip", "Title", "Tolerate", "Top",
		"Toss", "Total", "Touch", "Tour", "Trace", "Track", "Trade",
		"Trail", "Train", "Transfer", "Transform", "Translate", "Transmit",
		"Transport", "Trap", "Travel", "Treat", "Trick", "Trigger", "Trip",
		"Trouble", "Trust", "Try", "Turn", "Twist", "Type", "Undergo",
		"Undermine", "Understand", "Undertake", "Unfold", "Unify", "Unite",
		"Unveil", "Update", "Upgrade", "Uphold", "Upset", "Urge", "Use",
		"Utilize", "Value", "Vanish", "Vary", "Venture", "Verify", "View",
		"Visit", "Volunteer", "Vote", "Vow", "Wait", "Wake", "Walk",
		"Wander", "Want", "Warm", "Warn", "Warrant", "Wash", "Waste", "Watch",
		"Water", "Wave", "Weaken", "Wear", "Weave", "Weigh", "Welcome", "Whip",
		"Whisper", "Widen", "Win", "Wind", "Wipe", "Wish", "Withdraw",
		"Witness", "Wonder", "Work", "Worry", "Worship", "Wound", "Wrap",
		"Write", "Yell", "Yield",
	}
}

func verbTwo() []string {
	return []string{
		"Document", "Dominate", "Donate", "Double", "Doubt", "Download",
		"Draft", "Drag", "Drain", "Draw", "Dream", "Dress", "Drift", "Drink",
		"Drive", "Drop", "Dry", "Dub", "Dump", "Earn", "Ease", "Eat",
		"Echo", "Edit", "Educate", "Elect", "Elevate", "Eliminate", "Email",
		"Embark", "Embed", "Embody", "Embrace", "Emerge", "Emphasize", "Employ",
		"Empower", "Empty", "Enable", "Enact", "Encompass", "Encounter",
		"Encourage", "End", "Endorse", "Endure", "Enforce", "Engage", "Enhance",
		"Enjoy", "Enquire", "Enrich", "Enrol", "Ensue", "Ensure", "Enter",
		"Entertain", "Entitle", "Equal", "Equip", "Erect", "Erupt", "Escalate",
		"Escape", "Establish", "Estimate", "Evacuate", "Evaluate", "Evoke",
		"Evolve", "Exaggerate", "Examine", "Exceed", "Exchange", "Exclude",
		"Excuse", "Execute", "Exercise", "Exert", "Exhibit", "Exist", "Exit",
		"Expand", "Expect", "Experience", "Experiment", "Expire", "Explain",
		"Explode", "Exploit", "Explore", "Export", "Expose", "Express",
		"Extend", "Extract", "Face", "Facilitate", "Fade", "Fail", "Fall",
		"Fancy", "Farm", "Fasten", "Favour", "Fear", "Feature", "Feed", "Feel",
		"Fight", "Figure", "File", "Fill", "Film", "Filter", "Finance", "Find",
		"Fine", "Finish", "Fire", "Fish", "Fit", "Fix", "Flash", "Flee",
		"Float", "Flood", "Flourish", "Flow", "Fly", "Focus", "Fold", "Follow",
		"Forbid", "Force", "Forecast", "Forge", "Forget", "Forgive", "Form",
		"Formulate", "Foster", "Found", "Frame", "Free", "Freeze", "Frighten",
		"Fry", "Fuel", "Fulfil", "Function", "Fund", "Gain", "Gather", "Gaze",
		"Generate", "Get", "Give", "Glance", "Go", "Govern", "Grab", "Grade",
		"Graduate", "Grant", "Grasp", "Greet", "Grin", "Grind", "Grip", "Grow",
		"Guarantee", "Guard", "Guess", "Guide", "Hail", "Halt", "Hand",
		"Handle", "Hang", "Happen", "Harvest", "Haunt", "Have",
		"Head", "Heal", "Hear", "Heat", "Heighten", "Help", "Hesitate", "Hide",
		"Highlight", "Hint", "Hire", "Hit", "Hold", "Honour", "Hook", "Hope",
		"Host", "House", "Hunt", "Hurry", "Identify", "Ignore",
		"Illustrate", "Imagine", "Impact", "Implement", "Imply", "Import",
		"Impose", "Impress", "Improve", "Include", "Incorporate",
		"Increase", "Incur", "Indicate", "Induce", "Indulge", "Infect", "Infer",
		"Inflict", "Influence", "Inform", "Inherit", "Inhibit", "Initiate",
		"Inject", "Injure", "Insert", "Insist", "Inspect", "Inspire", "Install",
		"Instruct", "Insult", "Integrate", "Intend", "Intensify", "Interact",
		"Interest", "Interfere", "Interpret", "Interrupt", "Intervene",
		"Interview", "Introduce", "Invade", "Invent", "Invest", "Investigate",
		"Invite", "Invoke", "Involve", "Iron", "Isolate", "Issue",
		"Join", "Joke", "Judge", "Jump", "Justify", "Keep", "Key", "Kick",
		"Kiss", "Knock", "Know", "Label", "Lack", "Land",
		"Last", "Laugh", "Launch", "Lay", "Lead", "Leak", "Lean", "Leap",
		"Learn", "Leave", "Lecture", "Lend", "Let", "Level", "License", "Lift",
		"Light", "Like", "Limit", "Line", "Linger", "Link", "List", "Listen",
		"Live", "Load", "Lobby", "Locate", "Lock", "Log", "Look", "Loom",
		"Lose", "Love", "Lower", "Mail", "Maintain", "Make", "Manage",
	}
}

func verbThree() []string {
	return []string{
		"Abolish", "Absorb", "Accelerate", "Accept",
		"Access", "Accommodate", "Accompany", "Accomplish", "Account",
		"Accumulate", "Accuse", "Achieve", "Acknowledge", "Acquire", "Act",
		"Activate", "Adapt", "Add", "Address", "Adhere", "Adjust", "Administer",
		"Admire", "Admit", "Adopt", "Advance", "Advertise", "Advise",
		"Advocate", "Affect", "Afford", "Age", "Agree", "Aid", "Aim", "Alarm",
		"Alert", "Align", "Allege", "Allocate", "Allow", "Alter", "Amend",
		"Amount", "Analyse", "Announce", "Annoy", "Answer", "Anticipate",
		"Apologize", "Appeal", "Appear", "Applaud", "Apply", "Appoint",
		"Appreciate", "Approach", "Approve", "Argue", "Arise", "Arm", "Arrange",
		"Arrest", "Arrive", "Articulate", "Ask", "Aspire",
		"Assemble", "Assert", "Assess", "Assign", "Assist", "Associate",
		"Assume", "Assure", "Attach", "Attain", "Attempt", "Attend",
		"Attract", "Attribute", "Authorize", "Average", "Avoid", "Await",
		"Award", "Back", "Bake", "Balance", "Ban", "Bar", "Base", "Bat",
		"Battle", "Be", "Bear", "Beat", "Become", "Beg", "Begin", "Behave",
		"Believe", "Belong", "Bend", "Benefit", "Bet", "Betray", "Bid", "Bill",
		"Bind", "Bite", "Blame", "Blast", "Blend", "Bless", "Block",
		"Blow", "Board", "Boast", "Boil", "Book", "Boost", "Border",
		"Borrow", "Bother", "Bounce", "Bow", "Brand", "Breach", "Break",
		"Breathe", "Breed", "Bring", "Broadcast", "Brush", "Build", "Burn",
		"Burst", "Bury", "Buy", "Calculate", "Call", "Calm", "Camp", "Campaign",
		"Cancel", "Capture", "Care", "Carry", "Carve", "Cast", "Catch", "Cater",
		"Cause", "Cease", "Celebrate", "Centre", "Chain", "Chair", "Challenge",
		"Change", "Characterize", "Charge", "Chart", "Chase", "Chat", "Cheat",
		"Check", "Cheer", "Choose", "Chop", "Circle", "Circulate", "Cite",
		"Claim", "Clarify", "Classify", "Clean", "Clear", "Click", "Climb",
		"Cling", "Close", "Coach", "Coincide", "Collaborate", "Collapse",
		"Collect", "Combat", "Combine", "Come", "Comfort", "Command",
		"Commence", "Comment", "Commission", "Commit", "Communicate", "Compare",
		"Compel", "Compensate", "Compete", "Compile", "Complain", "Complement",
		"Complete", "Comply", "Compose", "Comprise", "Compromise", "Compute",
		"Conceal", "Concede", "Conceive", "Concentrate", "Concern", "Conclude",
		"Condemn", "Conduct", "Confer", "Confess", "Confine", "Confirm",
		"Conflict", "Confront", "Confuse", "Congratulate", "Connect", "Conquer",
		"Consent", "Conserve", "Consider", "Consist", "Consolidate",
		"Constitute", "Construct", "Consult", "Consume", "Contact", "Contain",
		"Contemplate", "Contend", "Contest", "Continue", "Contract", "Contrast",
		"Contribute", "Control", "Convert", "Convey", "Convict", "Convince",
		"Cook", "Cool", "Cooperate", "Coordinate", "Cope", "Copy", "Correct",
		"Correlate", "Correspond", "Cost", "Count", "Counter", "Cover", "Crack",
		"Craft", "Crash", "Crawl", "Create", "Credit", "Creep", "Criticize",
		"Cross", "Cruise", "Crush", "Cry", "Cultivate", "Cure", "Curve", "Cut",
		"Cycle", "Damage", "Dance", "Dare", "Date", "Deal", "Debate", "Decide",
		"Declare", "Decline", "Decorate", "Decrease", "Deem", "Defeat",
		"Defend", "Define", "Defy", "Delay", "Delete", "Delight", "Deliver",
		"Demand", "Demonstrate", "Denounce", "Deny", "Depart", "Depend",
		"Depict", "Deploy", "Deposit", "Deprive", "Derive", "Descend",
		"Describe", "Desert", "Deserve", "Design", "Designate", "Desire",
		"Destroy", "Detail", "Detain", "Detect", "Deteriorate", "Determine",
		"Devastate", "Develop", "Devise", "Devote", "Diagnose", "Dictate",
		"Differ", "Differentiate", "Dig", "Diminish", "Dip", "Direct",
		"Disagree", "Disappear", "Disappoint", "Discard", "Discharge",
		"Disclose", "Discount", "Discourage", "Discover", "Discuss", "Dislike",
		"Dismiss", "Displace", "Display", "Dispose", "Dispute", "Disrupt",
		"Dissolve", "Distinguish", "Distort", "Distract", "Distress",
		"Distribute", "Disturb", "Dive", "Divert", "Divide", "Divorce", "Do",
	}
}

func Verb() []string {
	verb := make([]string, 0)
	for _, fn := range []strSliceFnT{verbOne, verbTwo, verbThree} {
		verb = append(verb, fn()...)
	}

	return verb
}
