name: build
on: 
 push:
   branches:
     - develop
jobs:
  call-docker-build:
    uses: dictyBase/workflows/.github/workflows/docker-build-push.yaml@develop
    secrets: inherit
    with:
      repository: ${{ github.repository }}
      ref: ${{ github.ref_name }}
