name: Build
on: 
 push:
   branches:
     - develop
     - staging
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: set up golang
        uses: actions/setup-go@v1
        with:
            go-version: 1.11.13
      - name: check out code
        uses: actions/checkout@v1
      - name: build docker image
        run: docker build -t dictybase/modware-import:$(echo ${{ github.ref }} | sed -E 's/refs\/(heads|tags)\///')-$(git rev-parse --short HEAD) -f build/package/Dockerfile .
      - name: login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: push to docker hub
        run: docker push dictybase/modware-import:$(echo ${{ github.ref }} | sed -E 's/refs\/(heads|tags)\///')-$(git rev-parse --short HEAD)
