name: Lint Golang code
on:
  pull_request:
    branches-ignore:
      - master
jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: check out code
        uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21.5'
          cache: false
      - run: go version
      - name: run linter
        uses: golangci/golangci-lint-action@v3
        with: 
          version: v1.55.2
  call-pr-docker-build:
    needs: lint
    uses: dictyBase/workflows/.github/workflows/docker-build-push-pr.yaml@develop
    secrets: inherit
    with:
      repository: ${{ github.repository }}
      ref: ${{ github.event.pull_request.head.ref }}
