name: Lint and test coverage
on:
  pull_request:
    branches-ignore:
      - master
jobs:
  lint:
    uses: dictyBase/workflows/.github/workflows/golang-lint.yaml@develop
    with:
      repository: ${{ github.repository }}
      ref: ${{ github.event.pull_request.head.sha }}
      version: v2.6-alpine
  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: set up golang
        uses: actions/setup-go@v4
        with:
          go-version: 1.24
      - run: go version
      - name: check out code
        uses: actions/checkout@v4
      - name: unit test
        run: go test -shuffle on -covermode=atomic -coverprofile=profile.cov -v ./...
      - name: upload coverage to codecov
        uses: codecov/codecov-action@v4
        with:
          file: ./profile.cov
          token: ${{ secrets.CODECOV }}
